"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

export type BillingState={ok:boolean;message:string;receiptNo?:string};
const value=(form:FormData,key:string)=>String(form.get(key)||"").trim();
const fail=(message:string):BillingState=>({ok:false,message});
type BillingRefresh={column:"encounter_id"|"patient_id";value:string};

async function authorizedClient(facilityId:string){
 const supabase=await createClient();const{data:claims}=await supabase.auth.getClaims();const userId=claims?.claims.sub;
 if(!userId)return{error:"Sign in is required." as string};
 const{data:role}=await supabase.from("user_roles").select("facility_id").eq("user_id",userId).eq("facility_id",facilityId).eq("active",true).limit(1).maybeSingle();
 if(!role)return{error:"You are not assigned to this facility." as string};return{supabase,userId};
}
async function refreshPreparedCases(supabase:NonNullable<Awaited<ReturnType<typeof authorizedClient>>["supabase"]>,facilityId:string,refresh:BillingRefresh){
 const{data:cases,error}=await supabase.from("billing_cases").select("admission_id").eq("facility_id",facilityId).eq(refresh.column,refresh.value).not("admission_id","is",null).in("status",["draft","for_review","finalized","reopened"]);
 if(error)return error.message;
 for(const item of cases||[]){
  const{error:refreshError}=await supabase.rpc("prepare_billing_case",{target_admission:item.admission_id});
  if(refreshError)return refreshError.message;
 }
}
async function callRpc(facilityId:string,name:string,args:Record<string,unknown>,success:string,refresh?:BillingRefresh):Promise<BillingState>{
 const auth=await authorizedClient(facilityId);if(!auth.supabase)return fail(auth.error);const{data,error}=await auth.supabase.rpc(name,args);if(error)return fail(error.message);
 const refreshError=refresh?await refreshPreparedCases(auth.supabase,facilityId,refresh):undefined;
 revalidatePath("/billing");let receiptNo:string|undefined;if(typeof data==="string"&&name==="post_patient_payment")receiptNo=data;else if(data&&typeof data==="object"&&"receipt_no" in data)receiptNo=String((data as{receipt_no:unknown}).receipt_no);
 const message=receiptNo?`${success} Official receipt ${receiptNo}.`:success;
 return{ok:true,message:refreshError?`${message} Billing case refresh failed: ${refreshError}`:message,receiptNo};
}
export async function openCashierShift(_:BillingState,form:FormData){const facility=value(form,"facility_id"),amount=Number(value(form,"opening_cash"));if(!facility||!Number.isFinite(amount)||amount<0)return fail("Enter a valid non-negative opening cash amount.");return callRpc(facility,"open_cashier_shift",{target_facility:facility,opening_cash:amount},"Cashier shift opened.");}
export async function closeCashierShift(_:BillingState,form:FormData){const facility=value(form,"facility_id"),amount=Number(value(form,"actual_cash"));if(!value(form,"shift_id")||!Number.isFinite(amount)||amount<0)return fail("Enter a valid non-negative actual cash amount.");return callRpc(facility,"close_cashier_shift",{target_shift:value(form,"shift_id"),actual_cash:amount},"Shift reconciled and closed.");}
export async function postPatientCharge(_:BillingState,form:FormData){const facility=value(form,"facility_id"),encounter=value(form,"encounter_id"),amount=Number(value(form,"amount")),description=value(form,"description");if(!encounter||description.length<2||!Number.isFinite(amount)||amount<=0)return fail("Select an encounter and enter a description and positive charge amount.");return callRpc(facility,"post_patient_charge",{target_facility:facility,target_encounter:encounter,charge_description:description,charge_amount:amount},"Patient charge posted.",{column:"encounter_id",value:encounter});}
export async function postPatientPayment(_:BillingState,form:FormData){const facility=value(form,"facility_id"),patient=value(form,"patient_id"),amount=Number(value(form,"amount"));if(!patient||!value(form,"method_code")||!Number.isFinite(amount)||amount<=0)return fail("Select a patient, payment method, and positive payment amount.");const auth=await authorizedClient(facility);if(!auth.supabase)return fail(auth.error);const{data:shift}=await auth.supabase.from("cashier_shifts").select("id").eq("facility_id",facility).eq("cashier_id",auth.userId).eq("status","open").limit(1).maybeSingle();if(!shift)return fail("Open a cashier shift before accepting a payment.");return callRpc(facility,"post_patient_payment",{target_facility:facility,target_patient:patient,payment_amount:amount,method_code:value(form,"method_code"),external_ref:value(form,"external_ref")||null},"Payment posted and allocated.",{column:"patient_id",value:patient});}
export async function reverseLedgerEntry(_:BillingState,form:FormData){const facility=value(form,"facility_id"),reason=value(form,"reason");if(!value(form,"entry_id")||reason.length<5)return fail("A reversal reason of at least five characters is required.");return callRpc(facility,"reverse_ledger_entry",{target_entry:value(form,"entry_id"),reversal_reason:reason},"Ledger entry reversed.");}
export async function requestChargeAdjustment(_:BillingState,form:FormData){const facility=value(form,"facility_id"),entry=value(form,"entry_id"),amount=Number(value(form,"proposed_amount")),reason=value(form,"reason");if(!entry||!Number.isFinite(amount)||amount<0||reason.length<5)return fail("Enter a valid proposed price and a reason of at least five characters.");return callRpc(facility,"request_charge_adjustment",{target_entry:entry,proposed_price:amount,adjustment_reason:reason,attachment:value(form,"attachment_path")||null},"Price adjustment request submitted for approval.");}
export async function prepareBillingCase(_:BillingState,form:FormData){const facility=value(form,"facility_id"),admission=value(form,"admission_id");if(!admission)return fail("Select an admission to prepare.");return callRpc(facility,"prepare_billing_case",{target_admission:admission},"Accommodation accrued and billing case prepared for review.");}
export async function requestCoverageAdjustment(_:BillingState,form:FormData){const facility=value(form,"facility_id"),billingCase=value(form,"billing_case_id"),amount=Number(value(form,"amount")),description=value(form,"description");if(!billingCase||!value(form,"coverage_type")||description.length<3||!Number.isFinite(amount)||amount<=0)return fail("Enter a valid deduction type, description, and positive amount.");return callRpc(facility,"request_coverage_adjustment",{target_case:billingCase,coverage_code:value(form,"coverage_type"),coverage_reference:value(form,"reference_no")||null,coverage_description:description,amount},"Coverage or discount deduction submitted for approval.");}
export async function decideCoverageAdjustment(_:BillingState,form:FormData){const facility=value(form,"facility_id"),adjustment=value(form,"adjustment_id"),amount=Number(value(form,"approved_amount")),decision=value(form,"decision"),reason=value(form,"reason");if(!adjustment||!["approved","rejected"].includes(decision)||reason.length<5||(decision==="approved"&&(!Number.isFinite(amount)||amount<=0)))return fail("Enter a valid decision, amount, and reason of at least five characters.");return callRpc(facility,"decide_coverage_adjustment",{target_adjustment:adjustment,decision,approved_value:decision==="approved"?amount:0,decision_notes:reason},decision==="approved"?"Deduction approved and posted to the patient ledger.":"Deduction request rejected.");}
export async function setBillingCaseStatus(_:BillingState,form:FormData){const facility=value(form,"facility_id"),billingCase=value(form,"billing_case_id"),status=value(form,"next_status"),reason=value(form,"reason");if(!billingCase||!["finalized","cleared","reopened"].includes(status)||(status==="reopened"&&reason.length<5))return fail("Invalid billing status request or missing reopening reason.");const labels:Record<string,string>={finalized:"Patient bill finalized.",cleared:"Patient billing cleared.",reopened:"Patient bill reopened with an audit reason."};return callRpc(facility,"set_billing_case_status",{target_case:billingCase,next_status:status,change_reason:reason||null},labels[status]);}
