"use client";

import { useActionState, useMemo, useState } from "react";
import { Banknote, CircleDollarSign, FilePlus2, Plus, ReceiptText, Search, ShieldAlert, WalletCards, X } from "lucide-react";
import { SearchPicker } from "@/components/search-picker";
import { billingInitial, closeCashierShift, openCashierShift, postPatientCharge, postPatientPayment, reverseLedgerEntry } from "@/app/billing/actions";

type Patient={id:string;mrn:string;first_name:string;last_name:string};
type Account={id:string;patient_id:string;patients:Patient|Patient[]};
type Entry={id:string;account_id:string;encounter_id:string|null;kind:string;source_type:string;description:string;amount:number|string;currency:string;reverses_entry_id:string|null;posted_at:string;reason:string|null;patient_accounts:{facility_id:string;patients:Patient|Patient[]}|{facility_id:string;patients:Patient|Patient[]}[]};
type Payment={id:string;account_id:string;receipt_no:string;payment_method:string;amount:number|string;status:string;external_reference:string|null;posted_at:string;patient_accounts:{facility_id:string;patients:Patient|Patient[]}|{facility_id:string;patients:Patient|Patient[]}[]};
type Shift={id:string;cashier_id:string;opened_at:string;opening_amount:number|string;closed_at:string|null;expected_amount:number|string|null;actual_amount:number|string|null;status:string};
type Method={code:string;label:string};
const money=(n:number|string)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n)||0);
const one=<T,>(v:T|T[])=>Array.isArray(v)?v[0]:v;

export function BillingWorkspace({facilityId,userId,today,accounts,entries,payments,shifts,paymentMethods}:{facilityId:string;userId:string;today:string;accounts:Account[];entries:Entry[];payments:Payment[];shifts:Shift[];paymentMethods:Method[]}){
 const[dialog,setDialog]=useState<"open"|"close"|"charge"|"payment"|null>(null),[reversing,setReversing]=useState<Entry|null>(null),[query,setQuery]=useState("");
 const openShift=shifts.find(s=>s.cashier_id===userId&&s.status==="open");
 const reversed=new Set(entries.filter(e=>e.reverses_entry_id).map(e=>e.reverses_entry_id));
 const shown=useMemo(()=>{const q=query.toLowerCase().trim();return !q?entries:entries.filter(e=>{const p=one(one(e.patient_accounts)?.patients);return[p?.first_name,p?.last_name,p?.mrn,e.description,e.source_type].join(" ").toLowerCase().includes(q)})},[entries,query]);
 const balance=accounts.reduce((total,account)=>total+Math.max(0,entries.filter(e=>e.account_id===account.id).reduce((sum,e)=>sum+Number(e.amount),0)),0),todayPayments=payments.filter(p=>p.status==="posted"&&p.posted_at.slice(0,10)===today),collections=todayPayments.reduce((sum,p)=>sum+Number(p.amount),0);
 return <div className="billing-workspace">
  <section className={`shift-banner ${openShift?"open":"closed"}`}><div><span className="shift-icon"><WalletCards size={20}/></span><div><strong>{openShift?"Cashier shift open":"No open cashier shift"}</strong><small>{openShift?`Opened ${new Date(openShift.opened_at).toLocaleString()} · Opening cash ${money(openShift.opening_amount)}`:"Open a shift before accepting patient payments."}</small></div></div>{openShift?<button className="btn btn-secondary" onClick={()=>setDialog("close")}>Close & reconcile shift</button>:<button className="btn btn-primary" onClick={()=>setDialog("open")}><Plus size={15}/>Open shift</button>}</section>
  <section className="metric-grid"><Metric label="Open patient balance" value={money(balance)} note="Across all patient accounts" icon={<CircleDollarSign/>}/><Metric label="Today’s collections" value={money(collections)} note="Posted payments today" icon={<Banknote/>}/><Metric label="Transaction count" value={String(entries.length)} note="Loaded ledger entries" icon={<WalletCards/>}/><Metric label="Posted receipts" value={String(payments.filter(p=>p.status==="posted").length)} note="Official payment receipts" icon={<ReceiptText/>}/></section>
  <div className="billing-actions"><button className="btn btn-primary" onClick={()=>setDialog("payment")} disabled={!openShift}><CircleDollarSign size={15}/>Post payment</button><button className="btn btn-secondary" onClick={()=>setDialog("charge")}><FilePlus2 size={15}/>Post manual charge</button>{!openShift?<span><ShieldAlert size={14}/> Payments require an open shift</span>:null}</div>
  <section className="card billing-ledger"><div className="card-header"><div><h3>Patient account ledger</h3><small>Charges, payments, adjustments, and reversals</small></div><span className="badge blue">Live data</span></div><div className="billing-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient, MRN, description, or source"/></div><div className="billing-table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Patient / MRN</th><th>Description / source</th><th>Type</th><th>Amount</th><th>Action</th></tr></thead><tbody>{shown.map((entry,index)=>{const p=one(one(entry.patient_accounts)?.patients),eligible=(entry.kind==="charge"||entry.kind==="adjustment")&&!reversed.has(entry.id);return <tr key={entry.id} className={index%2?"alternate":""}><td>{new Date(entry.posted_at).toLocaleString()}</td><td className="name-cell"><strong>{p?.last_name}, {p?.first_name}</strong><span>{p?.mrn}</span></td><td className="name-cell"><strong>{entry.description}</strong><span>{entry.source_type.replaceAll("_"," ")}</span></td><td><span className={`badge ${entry.kind==="payment"?"green":entry.kind==="reversal"?"red":"blue"}`}>{entry.kind}</span></td><td className={Number(entry.amount)<0?"credit":"debit"}>{money(entry.amount)}</td><td>{eligible?<button className="table-action" onClick={()=>setReversing(entry)}>Reverse</button>:<span className="cell-muted">—</span>}</td></tr>})}{!shown.length?<tr><td colSpan={6} className="empty-state">No ledger entries match this search.</td></tr>:null}</tbody></table></div></section>
  <section className="card billing-history"><div className="card-header"><h3>Official receipt & payment history</h3><span>{payments.length} receipts</span></div><div className="billing-table-scroll payment-scroll"><table className="data-table"><thead><tr><th>Receipt number</th><th>Date</th><th>Patient / MRN</th><th>Method</th><th>External reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.map((payment,index)=>{const p=one(one(payment.patient_accounts)?.patients);return <tr key={payment.id} className={index%2?"alternate":""}><td className="link">{payment.receipt_no}</td><td>{new Date(payment.posted_at).toLocaleString()}</td><td className="name-cell"><strong>{p?.last_name}, {p?.first_name}</strong><span>{p?.mrn}</span></td><td>{paymentMethods.find(m=>m.code===payment.payment_method)?.label||payment.payment_method}</td><td>{payment.external_reference||"—"}</td><td><strong>{money(payment.amount)}</strong></td><td><span className={`badge ${payment.status==="posted"?"green":"red"}`}>{payment.status}</span></td></tr>})}{!payments.length?<tr><td colSpan={7} className="empty-state">No payments have been posted.</td></tr>:null}</tbody></table></div></section>
  {dialog?<BillingDialog mode={dialog} facilityId={facilityId} shift={openShift} methods={paymentMethods} close={()=>setDialog(null)}/>:null}{reversing?<ReverseDialog entry={reversing} facilityId={facilityId} close={()=>setReversing(null)}/>:null}
 </div>;
}
function Metric({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <article className="metric"><div className="metric-head">{label}<span className="metric-icon">{icon}</span></div><strong>{value}</strong><small>{note}</small></article>}
function Head({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Billing & cashier</p><h3>{title}</h3></div><button className="icon-btn" type="button" onClick={close} aria-label="Close"><X size={17}/></button></div>}
function BillingDialog({mode,facilityId,shift,methods,close}:{mode:"open"|"close"|"charge"|"payment";facilityId:string;shift?:Shift;methods:Method[];close:()=>void}){const fn=mode==="open"?openCashierShift:mode==="close"?closeCashierShift:mode==="charge"?postPatientCharge:postPatientPayment;const[state,action,pending]=useActionState(fn,billingInitial);const title={open:"Open cashier shift",close:"Close and reconcile shift",charge:"Post manual patient charge",payment:"Post patient payment"}[mode];return <div className="modal-backdrop"><section className="modal billing-modal" role="dialog" aria-modal="true"><Head title={title} close={close}/><form action={action} className="billing-form"><input type="hidden" name="facility_id" value={facilityId}/>{mode==="open"?<label className="wide">Opening cash amount<input name="opening_cash" type="number" min="0" step="0.01" required defaultValue="0"/></label>:null}{mode==="close"?<><input type="hidden" name="shift_id" value={shift?.id}/><div className="reconcile-summary wide"><span>Expected cash</span><strong>{money(shift?.expected_amount??shift?.opening_amount??0)}</strong></div><label className="wide">Actual cash counted<input name="actual_cash" type="number" min="0" step="0.01" required/></label></>:null}{mode==="charge"?<><div className="wide"><SearchPicker kind="encounter" name="encounter_id" label="Encounter" title="Select encounter" placeholder="No encounter selected" searchPlaceholder="Search encounter, patient, or MRN" required/></div><label className="wide">Charge description<input name="description" required minLength={2} maxLength={250}/></label><label className="wide">Charge amount<input name="amount" type="number" min="0.01" step="0.01" required/></label></>:null}{mode==="payment"?<><div className="wide"><SearchPicker kind="patient" name="patient_id" label="Patient" title="Select patient" placeholder="No patient selected" searchPlaceholder="Search patient name or MRN" required/></div><label>Payment amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Payment method<select name="method_code" required defaultValue=""><option value="" disabled>Select method</option>{methods.map(m=><option key={m.code} value={m.code}>{m.label}</option>)}</select></label><label className="wide">External reference<input name="external_ref" maxLength={100} placeholder="Optional bank, card, or e-wallet reference"/></label></>:null}{state.message?<div className={state.ok?"form-success wide":"form-error wide"} role="status">{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>{state.ok?"Done":"Cancel"}</button>{!state.ok?<button className="btn btn-primary" disabled={pending}>{pending?"Posting…":mode==="close"?"Close shift":mode==="open"?"Open shift":mode==="charge"?"Post charge":"Post & allocate payment"}</button>:null}</div></form></section></div>}
function ReverseDialog({entry,facilityId,close}:{entry:Entry;facilityId:string;close:()=>void}){const[state,action,pending]=useActionState(reverseLedgerEntry,billingInitial);return <div className="modal-backdrop"><section className="modal billing-modal" role="dialog" aria-modal="true"><Head title="Reverse ledger entry" close={close}/><form action={action} className="billing-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="entry_id" value={entry.id}/><div className="reversal-warning wide"><ShieldAlert size={18}/><div><strong>{entry.description}</strong><span>{money(entry.amount)} · This creates an audited counter-entry.</span></div></div><label className="wide">Reversal reason<textarea name="reason" required minLength={5} rows={4} maxLength={500}/><small>At least 5 characters are required.</small></label>{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>{state.ok?"Done":"Cancel"}</button>{!state.ok?<button className="btn btn-primary" disabled={pending}>{pending?"Reversing…":"Confirm reversal"}</button>:null}</div></form></section></div>}
