"use client";

import { useActionState, useMemo, useState } from "react";
import { Building2, Pencil, Plus, ToggleLeft, ToggleRight, X } from "lucide-react";
import { changeDepartmentStatus, changeProcedureRoomStatus, changeWardStatus, saveBed, saveDepartment, saveFacility, saveProcedureRoom, saveWard, type FacilityState } from "@/app/administration/facilities/actions";

export type FacilityRow={id:string;code:string;name:string;level:string;timezone:string;address:string|null;phone:string|null;email:string|null;license_no:string|null;version:number};
export type DepartmentRow={id:string;code:string;name:string;location:string|null;contact_no:string|null;operating_hours:string|null;status:string;version:number};
export type WardRow={id:string;code:string;name:string;floor_id:string|null;billing_service_id:string|null;status:string;version:number};
export type BedRow={id:string;ward_id:string;code:string;bed_type:string|null;daily_rate:number;gender_restriction:string;age_group:string;isolation_capable:boolean;status:string;version:number};
export type ProcedureRoomRow={id:string;room_kind:string;code:string;name:string;status:string;version:number};
type Option={id:string;name:string;code?:string};
const initial:FacilityState={ok:false,message:""};

export function FacilityWorkspace({facility,departments,wards,beds,floors,services,procedureRooms}:{facility:FacilityRow;departments:DepartmentRow[];wards:WardRow[];beds:BedRow[];floors:Option[];services:Option[];procedureRooms:ProcedureRoomRow[]}){
 const[facilityOpen,setFacilityOpen]=useState(false);const[department,setDepartment]=useState<DepartmentRow|null|undefined>();const[ward,setWard]=useState<WardRow|null|undefined>();const[bed,setBed]=useState<BedRow|null|undefined>();const[procedureRoom,setProcedureRoom]=useState<ProcedureRoomRow|null|undefined>();const[roomStatus,setRoomStatus]=useState<ProcedureRoomRow|null>(null);const[status,setStatus]=useState<{type:"department"|"ward";row:DepartmentRow|WardRow}|null>(null);
 const wardNames=useMemo(()=>new Map(wards.map(row=>[row.id,row.name])),[wards]);
 const bedCounts=useMemo(()=>{const counts=new Map<string,number>();for(const row of beds)counts.set(row.ward_id,(counts.get(row.ward_id)||0)+1);return counts;},[beds]);
 return <>
  <section className="admin-summary-grid"><Metric label="Departments" value={departments.length} note={`${departments.filter(row=>row.status==="active").length} active`}/><Metric label="Wards" value={wards.length} note={`${beds.filter(row=>row.status==="occupied").length} occupied beds`}/><Metric label="Beds" value={beds.length} note={`${beds.filter(row=>row.status==="available").length} available`}/></section>
  <section className="card facility-profile-card"><div className="card-header"><div><h3>{facility.name}</h3><p>{facility.code} · {facility.level} · {facility.timezone}</p></div><button className="btn btn-secondary" onClick={()=>setFacilityOpen(true)}><Pencil size={14}/>Edit facility</button></div><div className="facility-profile-grid"><Info label="Address" value={facility.address}/><Info label="Phone" value={facility.phone}/><Info label="Email" value={facility.email}/><Info label="License / accreditation" value={facility.license_no}/></div></section>
  <div className="administration-two-column">
   <section className="card"><div className="card-header"><div><h3>Departments</h3><p>Clinical and operational units, locations, contacts, and hours.</p></div><button className="btn btn-primary" onClick={()=>setDepartment(null)}><Plus size={14}/>Add department</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Department</th><th>Location / hours</th><th>Status</th><th>Actions</th></tr></thead><tbody>{departments.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.name}</strong><span>{row.code}{row.contact_no?` · ${row.contact_no}`:""}</span></td><td>{row.location||"—"}<span className="cell-muted">{row.operating_hours?` · ${row.operating_hours}`:""}</span></td><td><span className={`badge ${row.status==="active"?"green":"red"}`}>{row.status}</span></td><td><div className="admin-row-actions"><button className="btn btn-secondary" onClick={()=>setDepartment(row)}><Pencil size={13}/>Edit</button><button className="btn btn-secondary" onClick={()=>setStatus({type:"department",row})}>{row.status==="active"?<ToggleRight size={14}/>:<ToggleLeft size={14}/>}</button></div></td></tr>)}{!departments.length?<tr><td colSpan={4} className="empty-state">No departments configured.</td></tr>:null}</tbody></table></div></section>
   <section className="card"><div className="card-header"><div><h3>Wards</h3><p>Bed areas and optional room-charge mapping.</p></div><button className="btn btn-primary" onClick={()=>setWard(null)}><Plus size={14}/>Add ward</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Ward</th><th>Beds</th><th>Status</th><th>Actions</th></tr></thead><tbody>{wards.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.name}</strong><span>{row.code}</span></td><td>{bedCounts.get(row.id)||0}</td><td><span className={`badge ${row.status==="active"?"green":"red"}`}>{row.status}</span></td><td><div className="admin-row-actions"><button className="btn btn-secondary" onClick={()=>setWard(row)}><Pencil size={13}/>Edit</button><button className="btn btn-secondary" onClick={()=>setStatus({type:"ward",row})}>{row.status==="active"?<ToggleRight size={14}/>:<ToggleLeft size={14}/>}</button></div></td></tr>)}{!wards.length?<tr><td colSpan={4} className="empty-state">No wards configured.</td></tr>:null}</tbody></table></div></section>
  </div>
  <section className="card"><div className="card-header"><div><h3>OR / DR rooms</h3><p>Procedure rooms used when scheduling operating and delivery cases.</p></div><button className="btn btn-primary" onClick={()=>setProcedureRoom(null)}><Plus size={14}/>Add room</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Room</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{procedureRooms.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.name}</strong><span>{row.code}</span></td><td>{row.room_kind === "OR" ? "Operating room" : "Delivery room"}</td><td><span className={`badge ${row.status==="active"?"green":"red"}`}>{row.status}</span></td><td><div className="admin-row-actions"><button className="btn btn-secondary" onClick={()=>setProcedureRoom(row)}><Pencil size={13}/>Edit</button><button className="btn btn-secondary" onClick={()=>setRoomStatus(row)} aria-label={`${row.status==="active"?"Deactivate":"Activate"} ${row.name}`}>{row.status==="active"?<ToggleRight size={14}/>:<ToggleLeft size={14}/>}</button></div></td></tr>)}{!procedureRooms.length?<tr><td colSpan={4} className="empty-state">No OR or DR rooms configured.</td></tr>:null}</tbody></table></div></section>
  <section className="card"><div className="card-header"><div><h3>Beds</h3><p>ADT-controlled occupancy with governed maintenance and availability status.</p></div><button className="btn btn-primary" onClick={()=>setBed(null)}><Plus size={14}/>Add bed</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Bed</th><th>Ward</th><th>Type / restrictions</th><th>Daily rate</th><th>Status</th><th>Action</th></tr></thead><tbody>{beds.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.code}</strong><span>Version {row.version}</span></td><td>{wardNames.get(row.ward_id)||"Unknown"}</td><td>{row.bed_type||"Standard"}<span className="cell-muted"> · {row.gender_restriction} · {row.age_group}{row.isolation_capable?" · Isolation capable":""}</span></td><td>₱{Number(row.daily_rate||0).toLocaleString("en-PH",{minimumFractionDigits:2})}</td><td><span className={`badge ${row.status==="available"?"green":row.status==="occupied"?"amber":"red"}`}>{row.status}</span></td><td><button className="btn btn-secondary" disabled={row.status==="occupied"} title={row.status==="occupied"?"Occupancy is controlled by ADT":"Edit bed"} onClick={()=>setBed(row)}><Pencil size={13}/>Edit</button></td></tr>)}</tbody></table></div></section>
  {facilityOpen?<FacilityDialog facility={facility} close={()=>setFacilityOpen(false)}/>:null}
  {department!==undefined?<DepartmentDialog facilityId={facility.id} row={department||undefined} close={()=>setDepartment(undefined)}/>:null}
  {ward!==undefined?<WardDialog facilityId={facility.id} row={ward||undefined} floors={floors} services={services} close={()=>setWard(undefined)}/>:null}
  {bed!==undefined?<BedDialog facilityId={facility.id} row={bed||undefined} wards={wards.filter(row=>row.status==="active")} close={()=>setBed(undefined)}/>:null}
  {procedureRoom!==undefined?<ProcedureRoomDialog facilityId={facility.id} row={procedureRoom||undefined} close={()=>setProcedureRoom(undefined)}/>:null}
  {roomStatus?<ProcedureRoomStatusDialog facilityId={facility.id} row={roomStatus} close={()=>setRoomStatus(null)}/>:null}
  {status?<StatusDialog facilityId={facility.id} type={status.type} row={status.row} close={()=>setStatus(null)}/>:null}
 </>;
}

function Metric({label,value,note}:{label:string;value:number;note:string}){return <article className="metric"><div className="metric-head"><span>{label}</span><Building2 size={18}/></div><strong>{value}</strong><small>{note}</small></article>}
function Info({label,value}:{label:string;value:string|null}){return <div><span>{label}</span><strong>{value||"Not recorded"}</strong></div>}
function Head({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Facility governance</p><h3>{title}</h3></div><button type="button" className="icon-btn" onClick={close} aria-label="Close"><X size={17}/></button></div>}
function Feedback({state}:{state:FacilityState}){return state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}

function FacilityDialog({facility,close}:{facility:FacilityRow;close:()=>void}){const[state,action,pending]=useActionState(saveFacility,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title="Edit facility profile" close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facility.id}/><input type="hidden" name="version" value={facility.version}/><label>Facility name<input name="name" required defaultValue={facility.name}/></label><label>Level<input name="level" defaultValue={facility.level}/></label><label>Timezone<input name="timezone" defaultValue={facility.timezone}/></label><label>License / accreditation<input name="license_no" defaultValue={facility.license_no||""}/></label><label className="wide">Address<textarea name="address" rows={2} defaultValue={facility.address||""}/></label><label>Phone<input name="phone" defaultValue={facility.phone||""}/></label><label>Email<input type="email" name="email" defaultValue={facility.email||""}/></label><label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={2}/></label><Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function DepartmentDialog({facilityId,row,close}:{facilityId:string;row?:DepartmentRow;close:()=>void}){const[state,action,pending]=useActionState(saveDepartment,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={row?`Edit ${row.name}`:"Add department"} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="department_id" value={row?.id||""}/><input type="hidden" name="version" value={row?.version||0}/><label>Code<input name="code" required readOnly={Boolean(row)} defaultValue={row?.code||""}/></label><label>Name<input name="name" required defaultValue={row?.name||""}/></label><label>Location<input name="location" defaultValue={row?.location||""}/></label><label>Contact number<input name="contact_no" defaultValue={row?.contact_no||""}/></label><label className="wide">Operating hours<input name="operating_hours" placeholder="Example: Monday–Friday, 8:00 AM–5:00 PM" defaultValue={row?.operating_hours||""}/></label>{row?<label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={2}/></label>:null}<Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function WardDialog({facilityId,row,floors,services,close}:{facilityId:string;row?:WardRow;floors:Option[];services:Option[];close:()=>void}){const[state,action,pending]=useActionState(saveWard,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={row?`Edit ${row.name}`:"Add ward"} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="ward_id" value={row?.id||""}/><input type="hidden" name="version" value={row?.version||0}/><label>Code<input name="code" required readOnly={Boolean(row)} defaultValue={row?.code||""}/></label><label>Name<input name="name" required defaultValue={row?.name||""}/></label><label>Floor<select name="floor_id" defaultValue={row?.floor_id||""}><option value="">Not assigned</option>{floors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Room billing service<select name="billing_service_id" defaultValue={row?.billing_service_id||""}><option value="">Not mapped</option>{services.map(item=><option key={item.id} value={item.id}>{item.code?`${item.code} · `:""}{item.name}</option>)}</select></label>{row?<label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={2}/></label>:null}<Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function BedDialog({facilityId,row,wards,close}:{facilityId:string;row?:BedRow;wards:WardRow[];close:()=>void}){const[state,action,pending]=useActionState(saveBed,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={row?`Edit bed ${row.code}`:"Add bed"} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="bed_id" value={row?.id||""}/><input type="hidden" name="version" value={row?.version||0}/><label>Ward<select name="ward_id" required defaultValue={row?.ward_id||""}><option value="">Select ward</option>{wards.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Bed code<input name="code" required readOnly={Boolean(row)} defaultValue={row?.code||""}/></label><label>Bed type<input name="bed_type" defaultValue={row?.bed_type||""}/></label><label>Daily rate<input name="daily_rate" type="number" min="0" step="0.01" defaultValue={row?.daily_rate||0}/></label><label>Gender restriction<select name="gender_restriction" defaultValue={row?.gender_restriction||"any"}><option value="any">Any</option><option value="male">Male only</option><option value="female">Female only</option></select></label><label>Age group<select name="age_group" defaultValue={row?.age_group||"any"}><option value="any">Any</option><option value="adult">Adult</option><option value="pediatric">Pediatric</option><option value="neonatal">Neonatal</option><option value="geriatric">Geriatric</option></select></label><label>Status<select name="status" defaultValue={row?.status||"available"}><option value="available">Available</option><option value="cleaning">Cleaning</option><option value="isolation">Isolation</option><option value="maintenance">Maintenance</option><option value="blocked">Blocked</option><option value="inactive">Inactive</option></select></label><label className="check-label"><input type="checkbox" name="isolation_capable" defaultChecked={row?.isolation_capable}/>Isolation capable</label>{row?<label className="wide">Reason for modification / status change<textarea name="reason" required minLength={5} rows={2}/></label>:null}<Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function StatusDialog({facilityId,type,row,close}:{facilityId:string;type:"department"|"ward";row:DepartmentRow|WardRow;close:()=>void}){const action=type==="department"?changeDepartmentStatus:changeWardStatus;const[state,formAction,pending]=useActionState(action,initial);const next=row.status==="active"?"inactive":"active";return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={`${next==="active"?"Activate":"Deactivate"} ${row.name}`} close={close}/><form action={formAction} className="adt-dialog-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name={type==="department"?"department_id":"ward_id"} value={row.id}/><input type="hidden" name="status" value={next}/><p>Active clinical dependencies are protected and may block deactivation.</p><label>Reason<textarea name="reason" required minLength={5} rows={4}/></label><Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function ProcedureRoomDialog({facilityId,row,close}:{facilityId:string;row?:ProcedureRoomRow;close:()=>void}){const[state,action,pending]=useActionState(saveProcedureRoom,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={row?`Edit ${row.name}`:"Add OR / DR room"} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="room_id" value={row?.id||""}/><input type="hidden" name="version" value={row?.version||0}/><label>Room type<select name="room_kind" required defaultValue={row?.room_kind||""} disabled={Boolean(row)}><option value="">Select room type</option><option value="OR">Operating room</option><option value="DR">Delivery room</option></select>{row?<input type="hidden" name="room_kind" value={row.room_kind}/>:null}</label><label>Room code<input name="code" required minLength={2} readOnly={Boolean(row)} defaultValue={row?.code||""} placeholder="OR 1"/></label><label className="wide">Room name<input name="name" required minLength={2} defaultValue={row?.name||""} placeholder="Operating Room 1"/></label>{row?<label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={2}/></label>:null}<Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function ProcedureRoomStatusDialog({facilityId,row,close}:{facilityId:string;row:ProcedureRoomRow;close:()=>void}){const[state,action,pending]=useActionState(changeProcedureRoomStatus,initial);const next=row.status==="active"?"inactive":"active";return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={`${next==="active"?"Activate":"Deactivate"} ${row.name}`} close={close}/><form action={action} className="adt-dialog-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="room_id" value={row.id}/><input type="hidden" name="status" value={next}/><p>Rooms with scheduled or ongoing cases cannot be deactivated.</p><label>Reason<textarea name="reason" required minLength={5} rows={4}/></label><Feedback state={state}/><Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function Actions({pending,ok,close}:{pending:boolean;ok:boolean;close:()=>void}){return <div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>{ok?"Close":"Cancel"}</button>{!ok?<button className="btn btn-primary" disabled={pending}>{pending?"Saving…":"Save"}</button>:null}</div>}
