"use client";

import { useActionState, useEffect, useState } from "react";
import { ArrowRightLeft, Boxes, ChevronRight, ClipboardList, FilePlus2, PackageCheck, Pencil, Plus, Scale, Truck, X } from "lucide-react";
import { SearchPicker } from "@/components/search-picker";
import { addInventoryAttachment, adjustInventory, createSupplier, postInventoryStock, setSupplierStatus, transferInventory, updateSupplier, type InventoryState } from "@/app/inventory/actions";
import { createMedicine, type MedicineState } from "@/app/administration/medicines/actions";

export type Product={id:string;code:string;name:string;unit:string;reorder_level:number};
export type Store={id:string;code:string;name:string;store_type:string;status:string};
export type Supplier={id:string;code:string;name:string;contact_person:string|null;phone:string|null;email:string|null;address:string|null;status:string;version:number};
export type Lot={id:string;store_id:string;product_id:string;lot_no:string;expiry_date:string|null;quantity_on_hand:number;unit_cost:number;supplier_id:string|null;received_at:string|null};
export type Movement={id:string;store_id:string;product_id:string;lot_id:string|null;movement_type:string;quantity:number;source_type:string;source_id:string|null;reason:string|null;posted_at:string;reference_no:string|null;balance_after:number|null;unit_cost:number|null;supplier_id:string|null;remarks:string|null};
export type Reference={code:string;label:string;reference_groups:{code:string}|Array<{code:string}>};
export type Document={id:string;movement_id:string;display_name:string;description:string|null;uploaded_at:string;url:string};
type Tab="overview"|"beginning"|"receiving"|"adjustments"|"transfers"|"stock-card"|"suppliers";
const inventoryInitial:InventoryState={ok:false,message:""};

const tabs:[Tab,string][]=[["overview","Stock Overview"],["beginning","Beginning Balance"],["receiving","Receiving"],["adjustments","Adjustments"],["transfers","Transfers"],["stock-card","Stock Card"],["suppliers","Suppliers"]];
const refOptions=(references:Reference[],group:string)=>references.filter(option=>{const relation=Array.isArray(option.reference_groups)?option.reference_groups[0]:option.reference_groups;return relation?.code===group;});
export function InventoryWorkspace({facilityId,currentDate,products,stores,suppliers,lots,movements,references,documents}:{facilityId:string;currentDate:string;products:Product[];stores:Store[];suppliers:Supplier[];lots:Lot[];movements:Movement[];references:Reference[];documents:Document[]}){
 const[tab,setTab]=useState<Tab>("overview"),[entry,setEntry]=useState<"beginning_balance"|"receipt"|null>(null),[adjusting,setAdjusting]=useState(false),[transferring,setTransferring]=useState(false),[supplierMode,setSupplierMode]=useState<Supplier|null|"new">(null),[selectedLot,setSelectedLot]=useState<Lot|null>(null),[attachMovement,setAttachMovement]=useState<Movement|null>(null);
 const[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[location,setLocation]=useState("all");
 const product=(id:string)=>products.find(item=>item.id===id),store=(id:string)=>stores.find(item=>item.id===id),supplier=(id:string|null)=>suppliers.find(item=>item.id===id);
 const stockStatus=(lot:Lot)=>{if(Number(lot.quantity_on_hand)<=0)return"out";if(lot.expiry_date&&lot.expiry_date<currentDate)return"expired";const days=lot.expiry_date?Math.ceil((new Date(lot.expiry_date).getTime()-new Date(currentDate).getTime())/86400000):9999;if(days<=90)return"near_expiry";if(Number(lot.quantity_on_hand)<=Number(product(lot.product_id)?.reorder_level||0))return"low";return"in_stock";};
 const shownLots=lots.filter(lot=>{const item=products.find(p=>p.id===lot.product_id),q=query.toLowerCase();return(!q||`${item?.code} ${item?.name} ${lot.lot_no}`.toLowerCase().includes(q))&&(status==="all"||stockStatus(lot)===status)&&(location==="all"||lot.store_id===location)});
 const totals={medicines:new Set(lots.map(l=>l.product_id)).size,low:lots.filter(l=>stockStatus(l)==="low").length,expiry:lots.filter(l=>stockStatus(l)==="near_expiry").length,out:lots.filter(l=>stockStatus(l)==="out").length};
 const tabMovements=(source?:string,type?:string)=>movements.filter(m=>(!source||m.source_type===source)&&(!type||m.movement_type===type));
 const movementTable=(rows:Movement[])=><MovementTable rows={rows} products={products} stores={stores} lots={lots} suppliers={suppliers} documents={documents} attach={setAttachMovement}/>;
 return <>
  <div className="inventory-tabs" role="tablist">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==="overview"?<><div className="inventory-actions"><button className="btn btn-primary" onClick={()=>setEntry("receipt")}><Plus size={15}/>Receive stock</button><button className="btn btn-secondary" onClick={()=>setAdjusting(true)}><Scale size={15}/>Stock adjustment</button><button className="btn btn-secondary" onClick={()=>setTransferring(true)}><ArrowRightLeft size={15}/>Transfer stock</button></div><section className="inventory-metrics"><Metric label="Total medicines" value={totals.medicines} tone="teal" icon={<Boxes/>}/><Metric label="Low stock" value={totals.low} tone="amber" icon={<Scale/>}/><Metric label="Near expiry" value={totals.expiry} tone="blue" icon={<ClipboardList/>}/><Metric label="Out of stock" value={totals.out} tone="red" icon={<X/>}/></section><section className="card"><div className="card-header"><h3>Medicine stock and lot monitoring</h3><span className="badge blue">Live data</span></div><div className="inventory-filters"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Medicine, code, or lot"/></label><label>Stock status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All stock</option><option value="in_stock">In stock</option><option value="low">Low stock</option><option value="near_expiry">Near expiry</option><option value="expired">Expired</option><option value="out">Out of stock</option></select></label><label>Storage location<select value={location} onChange={e=>setLocation(e.target.value)}><option value="all">All locations</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><LotTable lots={shownLots} products={products} stores={stores} statusFor={stockStatus} open={setSelectedLot}/></section></>:null}
  {tab==="beginning"?<InventorySection title="Beginning balance entries" action={<button className="btn btn-primary" onClick={()=>setEntry("beginning_balance")}><Plus size={15}/>Post beginning balance</button>}>{movementTable(tabMovements("beginning_balance"))}</InventorySection>:null}
  {tab==="receiving"?<InventorySection title="Stock receiving history" action={<button className="btn btn-primary" onClick={()=>setEntry("receipt")}><Truck size={15}/>Receive stock</button>}>{movementTable(tabMovements("receipt"))}</InventorySection>:null}
  {tab==="adjustments"?<InventorySection title="Inventory adjustments" action={<button className="btn btn-primary" onClick={()=>setAdjusting(true)}><Scale size={15}/>New adjustment</button>}>{movementTable(tabMovements("inventory_adjustment"))}</InventorySection>:null}
  {tab==="transfers"?<InventorySection title="Stock transfers" action={<button className="btn btn-primary" onClick={()=>setTransferring(true)}><ArrowRightLeft size={15}/>Transfer stock</button>}>{movementTable(tabMovements("inventory_transfer","transfer_out"))}</InventorySection>:null}
  {tab==="stock-card"?<InventorySection title="Inventory stock card">{movementTable(movements)}</InventorySection>:null}
  {tab==="suppliers"?<InventorySection title="Supplier master list" action={<button className="btn btn-primary" onClick={()=>setSupplierMode("new")}><Plus size={15}/>Add supplier</button>}><SupplierTable suppliers={suppliers} facilityId={facilityId} edit={setSupplierMode}/></InventorySection>:null}
  {entry?<StockEntryDialog mode={entry} facilityId={facilityId} stores={stores} suppliers={suppliers.filter(s=>s.status==="active")} close={()=>setEntry(null)}/>:null}
  {adjusting?<AdjustmentDialog facilityId={facilityId} lots={lots} products={products} stores={stores} references={references} close={()=>setAdjusting(false)}/>:null}
  {transferring?<TransferDialog facilityId={facilityId} lots={lots.filter(l=>Number(l.quantity_on_hand)>0)} products={products} stores={stores} close={()=>setTransferring(false)}/>:null}
  {supplierMode?<SupplierDialog facilityId={facilityId} supplier={supplierMode==="new"?undefined:supplierMode} close={()=>setSupplierMode(null)}/>:null}
  {selectedLot?<LotDetail lot={selectedLot} product={product(selectedLot.product_id)} store={store(selectedLot.store_id)} supplier={supplier(selectedLot.supplier_id)} movements={movements.filter(m=>m.lot_id===selectedLot.id)} close={()=>setSelectedLot(null)}/>:null}
  {attachMovement?<AttachmentDialog movement={attachMovement} facilityId={facilityId} close={()=>setAttachMovement(null)}/>:null}
 </>;
}

function Metric({label,value,tone,icon}:{label:string;value:number;tone:string;icon:React.ReactNode}){return <article className={`inventory-metric ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>}
function InventorySection({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="card inventory-section"><div className="card-header"><h3>{title}</h3>{action}</div>{children}</section>}
function LotTable({lots,products,stores,statusFor,open}:{lots:Lot[];products:Product[];stores:Store[];statusFor:(lot:Lot)=>string;open:(lot:Lot)=>void}){const labels:Record<string,[string,string]>={in_stock:["In stock","green"],low:["Low stock","amber"],near_expiry:["Near expiry","blue"],expired:["Expired","red"],out:["Out of stock","red"]};return <div className="table-wrap"><table className="data-table inventory-table"><thead><tr><th>Medicine</th><th>Lot / Batch</th><th>Expiry</th><th>Location</th><th>Available</th><th>Reorder level</th><th>Status</th><th>Action</th></tr></thead><tbody>{lots.map(lot=>{const p=products.find(x=>x.id===lot.product_id),s=stores.find(x=>x.id===lot.store_id),label=labels[statusFor(lot)];return <tr key={lot.id}><td className="name-cell"><strong>{p?.name}</strong><span>{p?.code} · {p?.unit}</span></td><td>{lot.lot_no}</td><td>{lot.expiry_date||"No expiry"}</td><td>{s?.name}</td><td><strong>{lot.quantity_on_hand}</strong></td><td>{p?.reorder_level}</td><td><span className={`badge ${label[1]}`}>{label[0]}</span></td><td><button className="btn btn-secondary" onClick={()=>open(lot)}>View / manage <ChevronRight size={14}/></button></td></tr>})}{!lots.length?<tr><td colSpan={8} className="empty-state">No stock lots match the selected filters.</td></tr>:null}</tbody></table></div>}
function MovementTable({rows,products,stores,lots,suppliers,documents,attach}:{rows:Movement[];products:Product[];stores:Store[];lots:Lot[];suppliers:Supplier[];documents:Document[];attach:(movement:Movement)=>void}){return <div className="table-wrap"><table className="data-table inventory-table"><thead><tr><th>Date</th><th>Reference</th><th>Medicine / Lot</th><th>Transaction</th><th>IN</th><th>OUT</th><th>Balance</th><th>Location</th><th>Documents</th></tr></thead><tbody>{rows.map(m=>{const p=products.find(x=>x.id===m.product_id),l=lots.find(x=>x.id===m.lot_id),s=stores.find(x=>x.id===m.store_id),docs=documents.filter(x=>x.movement_id===m.id);return <tr key={m.id}><td>{new Date(m.posted_at).toLocaleDateString()}</td><td><strong>{m.reference_no||"—"}</strong></td><td className="name-cell"><strong>{p?.name}</strong><span>{l?.lot_no||"No lot"}{m.supplier_id?` · ${suppliers.find(x=>x.id===m.supplier_id)?.name||"Supplier"}`:""}</span></td><td><span className="badge blue">{m.source_type.replaceAll("_"," ")}</span></td><td>{Number(m.quantity)>0?m.quantity:"—"}</td><td>{Number(m.quantity)<0?Math.abs(Number(m.quantity)):"—"}</td><td>{m.balance_after??"—"}</td><td>{s?.name}</td><td><div className="inventory-doc-actions">{docs.map(d=><a key={d.id} href={d.url} target="_blank" rel="noreferrer">{d.display_name}</a>)}<button className="table-action" onClick={()=>attach(m)}><FilePlus2 size={13}/>Attach</button></div></td></tr>})}{!rows.length?<tr><td colSpan={9} className="empty-state">No inventory transactions recorded yet.</td></tr>:null}</tbody></table></div>}

function ModalHead({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Inventory workflow</p><h3>{title}</h3></div><button className="icon-btn" type="button" onClick={close} aria-label="Close"><X size={17}/></button></div>}
function StockEntryDialog({mode,facilityId,stores,suppliers,close}:{mode:"beginning_balance"|"receipt";facilityId:string;stores:Store[];suppliers:Supplier[];close:()=>void}){
 const[state,action,pending]=useActionState(postInventoryStock,inventoryInitial);
 const[addingMedicine,setAddingMedicine]=useState(false);
 const[selectedMedicine,setSelectedMedicine]=useState<{value:string;label:string;meta:string}|undefined>();
 return <div className="modal-backdrop"><section className="modal inventory-modal" role="dialog" aria-modal="true"><ModalHead title={mode==="beginning_balance"?"Post beginning balance":"Receive stock"} close={close}/><form action={action} className="inventory-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="source_kind" value={mode}/><div className="inventory-medicine-select"><SearchPicker key={selectedMedicine?.value||"medicine-picker"} kind="medicine" name="product_id" label="Medicine" title="Select medicine" placeholder="No medicine selected" searchPlaceholder="Search medicine code, name, or unit" defaultValue={selectedMedicine?.value} initialOption={selectedMedicine} required/><button type="button" className="btn btn-secondary add-medicine-inline" onClick={()=>setAddingMedicine(true)}><Plus size={15}/>Add new medicine</button></div><label>Storage location<select name="store_id" required defaultValue=""><option value="" disabled>Select location</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Supplier<select name="supplier_id" defaultValue=""><option value="">None / not applicable</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Lot / batch number<input name="lot_no" required maxLength={80}/></label><label>Expiry date<input type="date" name="expiry_date"/></label><label>Quantity<input type="number" min="0.001" step="0.001" name="quantity" required/></label><label>Unit cost<input type="number" min="0" step="0.01" name="unit_cost" required defaultValue="0"/></label><label>Reference number<input name="reference_no" maxLength={80} placeholder="Auto-generated if blank"/></label><label className="wide">Remarks<textarea name="remarks" rows={3} maxLength={1000}/></label>{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending||state.ok} className="btn btn-primary"><PackageCheck size={15}/>{pending?"Posting…":"Post inventory"}</button></div></form></section>{addingMedicine?<QuickMedicineDialog facilityId={facilityId} close={()=>setAddingMedicine(false)} created={medicine=>{setSelectedMedicine({value:medicine.id,label:medicine.name,meta:`${medicine.code} · ${medicine.unit}`});setAddingMedicine(false)}}/>:null}</div>;
}

function QuickMedicineDialog({facilityId,close,created}:{facilityId:string;close:()=>void;created:(medicine:{id:string;code:string;name:string;unit:string})=>void}){
 const initial:MedicineState={ok:false,message:""};
 const[state,action,pending]=useActionState(createMedicine,initial);
 useEffect(()=>{if(state.ok&&state.medicine)created(state.medicine)},[state,created]);
 return <div className="modal-backdrop nested-modal"><section className="modal inventory-modal" role="dialog" aria-modal="true" aria-label="Add new medicine"><ModalHead title="Add new medicine" close={close}/><form action={action} className="inventory-form"><input type="hidden" name="facility_id" value={facilityId}/><label>Medicine code<input required minLength={2} maxLength={30} name="code" placeholder="Example: MED-001"/></label><label>Medicine name<input required minLength={2} maxLength={200} name="name"/></label><label>Unit<input required maxLength={40} name="unit" placeholder="tablet, capsule, mL"/></label><label>Reorder level<input required type="number" min="0" step="0.001" name="reorder_level" defaultValue="0"/></label>{state.message&&!state.ok?<div className="form-error wide">{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending} className="btn btn-primary">{pending?"Saving…":"Save and select medicine"}</button></div></form></section></div>;
}
function AdjustmentDialog({facilityId,lots,products,stores,references,close}:{facilityId:string;lots:Lot[];products:Product[];stores:Store[];references:Reference[];close:()=>void}){const[state,action,pending]=useActionState(adjustInventory,inventoryInitial);return <div className="modal-backdrop"><section className="modal inventory-modal"><ModalHead title="Inventory adjustment" close={close}/><form action={action} className="inventory-form"><input type="hidden" name="facility_id" value={facilityId}/><label className="wide">Medicine lot<select name="lot_id" required defaultValue=""><option value="" disabled>Select stock lot</option>{lots.map(l=><option key={l.id} value={l.id}>{products.find(p=>p.id===l.product_id)?.name} · {l.lot_no} · {stores.find(s=>s.id===l.store_id)?.name} · Current {l.quantity_on_hand}</option>)}</select></label><label>Actual physical quantity<input type="number" min="0" step="0.001" name="actual_quantity" required/></label><label>Adjustment reason<select name="reason_code" required defaultValue=""><option value="" disabled>Select reason</option>{refOptions(references,"inventory_adjustment_reason").map(r=><option key={r.code} value={r.code}>{r.label}</option>)}</select></label><label className="wide">Detailed remarks<textarea name="remarks" minLength={5} rows={4} required/></label>{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending||state.ok} className="btn btn-primary">{pending?"Posting…":"Post adjustment"}</button></div></form></section></div>}
function TransferDialog({facilityId,lots,products,stores,close}:{facilityId:string;lots:Lot[];products:Product[];stores:Store[];close:()=>void}){const[state,action,pending]=useActionState(transferInventory,inventoryInitial);return <div className="modal-backdrop"><section className="modal inventory-modal"><ModalHead title="Transfer stock" close={close}/><form action={action} className="inventory-form"><input type="hidden" name="facility_id" value={facilityId}/><label className="wide">Source lot<select name="lot_id" required defaultValue=""><option value="" disabled>Select source lot</option>{lots.map(l=><option key={l.id} value={l.id}>{products.find(p=>p.id===l.product_id)?.name} · {l.lot_no} · {stores.find(s=>s.id===l.store_id)?.name} · Available {l.quantity_on_hand}</option>)}</select></label><label>Destination location<select name="destination_store" required defaultValue=""><option value="" disabled>Select destination</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Transfer quantity<input type="number" min="0.001" step="0.001" name="quantity" required/></label><label className="wide">Transfer reason<textarea name="remarks" minLength={5} rows={4} required/></label>{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending||state.ok} className="btn btn-primary">{pending?"Posting…":"Confirm transfer"}</button></div></form></section></div>}

function SupplierTable({suppliers,facilityId,edit}:{suppliers:Supplier[];facilityId:string;edit:(supplier:Supplier)=>void}){return <div className="table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Supplier</th><th>Contact</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>{suppliers.map(s=><tr key={s.id}><td><strong>{s.code}</strong></td><td className="name-cell"><strong>{s.name}</strong><span>{s.address||"No address"}</span></td><td>{s.contact_person||"—"} · {s.phone||"—"}</td><td>{s.email||"—"}</td><td><span className={`badge ${s.status==="active"?"green":"red"}`}>{s.status}</span></td><td><div className="supplier-actions"><button className="table-action" onClick={()=>edit(s)}><Pencil size={13}/>Edit</button><form action={setSupplierStatus}><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="supplier_id" value={s.id}/><input type="hidden" name="status" value={s.status==="active"?"inactive":"active"}/><input name="reason" required minLength={5} placeholder="Reason"/><button className="table-action">{s.status==="active"?"Archive":"Restore"}</button></form></div></td></tr>)}{!suppliers.length?<tr><td colSpan={6} className="empty-state">No suppliers configured.</td></tr>:null}</tbody></table></div>}
function SupplierDialog({facilityId,supplier,close}:{facilityId:string;supplier?:Supplier;close:()=>void}){const[state,action,pending]=useActionState(supplier?updateSupplier:createSupplier,inventoryInitial);return <div className="modal-backdrop"><section className="modal inventory-modal"><ModalHead title={supplier?`Edit ${supplier.code}`:"Add supplier"} close={close}/><form action={action} className="inventory-form"><input type="hidden" name="facility_id" value={facilityId}/>{supplier?<><input type="hidden" name="supplier_id" value={supplier.id}/><input type="hidden" name="version" value={supplier.version}/></>:null}<label>Supplier code<input name="code" required={!supplier} readOnly={!!supplier} defaultValue={supplier?.code}/></label><label>Supplier name<input name="name" required defaultValue={supplier?.name}/></label><label>Contact person<input name="contact_person" defaultValue={supplier?.contact_person||""}/></label><label>Phone<input name="phone" defaultValue={supplier?.phone||""}/></label><label>Email<input type="email" name="email" defaultValue={supplier?.email||""}/></label><label className="wide">Address<textarea name="address" rows={3} defaultValue={supplier?.address||""}/></label>{supplier?<label className="wide">Modification reason<textarea name="reason" required minLength={5} rows={3}/></label>:null}{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending||state.ok} className="btn btn-primary">{pending?"Saving…":"Save supplier"}</button></div></form></section></div>}
function LotDetail({lot,product,store,supplier,movements,close}:{lot:Lot;product?:Product;store?:Store;supplier?:Supplier;movements:Movement[];close:()=>void}){return <div className="modal-backdrop"><section className="modal inventory-detail-modal"><ModalHead title={`${product?.name||"Stock"} · ${lot.lot_no}`} close={close}/><div className="inventory-detail-body"><div className="order-summary-grid"><Info label="Medicine" value={`${product?.name||"—"} · ${product?.code||""}`}/><Info label="Location" value={store?.name||"—"}/><Info label="Available" value={`${lot.quantity_on_hand} ${product?.unit||""}`}/><Info label="Unit cost" value={`₱${Number(lot.unit_cost).toFixed(2)}`}/><Info label="Expiry" value={lot.expiry_date||"No expiry"}/><Info label="Supplier" value={supplier?.name||"Not recorded"}/></div><h4>Lot movement history</h4><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Quantity</th><th>Balance</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.posted_at).toLocaleString()}</td><td>{m.reference_no||"—"}</td><td>{m.source_type.replaceAll("_"," ")}</td><td>{m.quantity}</td><td>{m.balance_after??"—"}</td></tr>)}</tbody></table></div></div></section></div>}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function AttachmentDialog({movement,facilityId,close}:{movement:Movement;facilityId:string;close:()=>void}){const[state,action,pending]=useActionState(async(_:typeof inventoryInitial,form:FormData)=>addInventoryAttachment(form),inventoryInitial);return <div className="modal-backdrop"><section className="modal inventory-modal"><ModalHead title={`Attach document · ${movement.reference_no||"Movement"}`} close={close}/><form action={action} className="inventory-form"><input type="hidden" name="movement_id" value={movement.id}/><input type="hidden" name="facility_id" value={facilityId}/><label className="wide">Document title<input name="display_name" required minLength={2}/></label><label className="wide">Description<textarea name="description" rows={3}/></label><label className="wide">File<input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png" required/><small>PDF, JPG, or PNG up to 5 MB.</small></label>{state.message?<div className={state.ok?"form-success wide":"form-error wide"}>{state.message}</div>:null}<div className="form-actions wide"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={pending||state.ok} className="btn btn-primary">{pending?"Uploading…":"Upload attachment"}</button></div></form></section></div>}
