"use client";

import { useMemo, useState } from "react";
import { Activity, BedDouble, CircleDollarSign, ClipboardList, Download, PackageSearch, Printer, Search, ShieldCheck, Stethoscope } from "lucide-react";
import { formatDateOnly, formatDateTime } from "@/lib/format";

type Operation={business_date:string;encounters:number;opd_visits:number;admissions:number;discharges:number;orders:number;prescriptions:number;charges:number|string;collections:number|string};
type Revenue={business_date:string;source_type:string;gross_charges:number|string;deductions:number|string;transaction_count:number};
type Balance={billing_case_id:string;status:string;admission_no:string|null;mrn:string;last_name:string;first_name:string;gross_charges:number|string;approved_deductions:number|string;payments:number|string;final_balance:number|string;pending_deductions:number|string;ageing_band:string};
type Bed={ward_code:string;ward_name:string;total_beds:number;occupied_beds:number;available_beds:number;unavailable_beds:number;occupancy_percent:number|string|null};
type Disease={census_month:string;encounter_type:string;code:string|null;description:string;chapter:string|null;category:string|null;disease_class:string|null;reportable:boolean|null;classification:string;encounter_count:number;patient_count:number;male_patients:number;female_patients:number};
type Inventory={store_name:string;product_code:string;product_name:string;unit:string;quantity_on_hand:number|string;reorder_level:number|string;nearest_expiry:string|null;stock_value:number|string;risk_status:string};
type Audit={id:string;actor_id:string|null;created_at:string;event_type:string;object_type:string|null;result:string;reason:string|null};
type Tab="operations"|"revenue"|"balances"|"disease"|"inventory"|"audit";
type Row=Record<string,string|number|boolean|null|undefined>;
const money=(value:number|string)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(value)||0);
const number=(value:number|string)=>new Intl.NumberFormat("en-PH").format(Number(value)||0);
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const tabs=[['operations','Operations',Activity],['revenue','Revenue',CircleDollarSign],['balances','Patient balances',ClipboardList],['disease','Disease census',Stethoscope],['inventory','Inventory risk',PackageSearch],['audit','Audit activity',ShieldCheck]] as const;

export function ReportsWorkspace({from,to,operations,revenue,balances,beds,diseases,inventory,audit}:{from:string;to:string;operations:Operation[];revenue:Revenue[];balances:Balance[];beds:Bed[];diseases:Disease[];inventory:Inventory[];audit:Audit[]}){
 const[tab,setTab]=useState<Tab>("operations"),[query,setQuery]=useState("");
 const totals=useMemo(()=>operations.reduce((sum,row)=>({encounters:sum.encounters+Number(row.encounters),admissions:sum.admissions+Number(row.admissions),collections:sum.collections+Number(row.collections),charges:sum.charges+Number(row.charges)}),{encounters:0,admissions:0,collections:0,charges:0}),[operations]);
 const openBalance=balances.reduce((sum,row)=>sum+Math.max(Number(row.final_balance),0),0),occupancy=beds.reduce((sum,row)=>sum+Number(row.occupied_beds),0),totalBeds=beds.reduce((sum,row)=>sum+Number(row.total_beds),0);
 const activeRows:Row[]=tab==="operations"?operations:tab==="revenue"?revenue:tab==="balances"?balances:tab==="disease"?diseases:tab==="inventory"?inventory:audit.map(row=>({...row,actor:row.actor_id?`User ${row.actor_id.slice(0,8)}`:"System"}));
 const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return term?activeRows.filter(row=>Object.values(row).some(value=>String(value??"").toLowerCase().includes(term))):activeRows},[activeRows,query]);
 const exportCsv=()=>{if(!filtered.length)return;const keys=Object.keys(filtered[0]).filter(key=>key!=="profiles"),escape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`,csv=[keys.map(escape).join(","),...filtered.map(row=>keys.map(key=>escape(row[key])).join(","))].join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`hospital-one-${tab}-${from}-to-${to}.csv`;anchor.click();URL.revokeObjectURL(url)};
 return <div className="reports-workspace">
  <form className="report-toolbar"><label>From<input type="date" name="from" defaultValue={from}/></label><label>To<input type="date" name="to" defaultValue={to}/></label><button className="btn btn-primary">Apply period</button><button type="button" className="btn btn-secondary" onClick={()=>window.print()}><Printer size={14}/>Print</button><button type="button" className="btn btn-secondary" onClick={exportCsv}><Download size={14}/>Export CSV</button></form>
  <section className="metric-grid"><Metric title="Encounters" value={number(totals.encounters)} note={`${from} to ${to}`} icon={<Activity/>}/><Metric title="Admissions" value={number(totals.admissions)} note={`${occupancy}/${totalBeds} beds currently occupied`} icon={<BedDouble/>}/><Metric title="Gross charges" value={money(totals.charges)} note="Charges within selected period" icon={<CircleDollarSign/>}/><Metric title="Outstanding balance" value={money(openBalance)} note={`${balances.filter(row=>Number(row.final_balance)>0).length} patient bills`} icon={<ClipboardList/>}/></section>
  <nav className="report-tabs" aria-label="Report categories">{tabs.map(([value,text,Icon])=><button key={value} type="button" className={tab===value?"active":""} onClick={()=>{setTab(value);setQuery("")}}><Icon size={15}/>{text}</button>)}</nav>
  {tab==="operations"?<OperationsChart rows={operations}/>:null}
  {tab==="operations"?<BedOccupancy rows={beds}/>:null}
  <section className="card report-table"><div className="card-header"><div><h3>{label(tab)} report</h3><small>{filtered.length} records · facility-scoped live data</small></div><label className="report-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filter current report" aria-label="Filter current report"/></label></div><div className="report-table-scroll"><ReportTable tab={tab} rows={filtered}/></div></section>
 </div>;
}

function Metric({title,value,note,icon}:{title:string;value:string;note:string;icon:React.ReactNode}){return <article className="metric"><div className="metric-head">{title}<span className="metric-icon">{icon}</span></div><strong>{value}</strong><small>{note}</small></article>}
function OperationsChart({rows}:{rows:Operation[]}){const recent=rows.slice(-14),max=Math.max(1,...recent.map(row=>Number(row.encounters)));return <section className="card report-chart"><div className="card-header"><div><h3>Patient activity trend</h3><small>Latest {recent.length} days within the selected period</small></div><span className="badge blue">Encounters</span></div><div className="trend-bars">{recent.map(row=><div className="trend-column" key={row.business_date} title={`${row.business_date}: ${row.encounters} encounters`}><span>{row.encounters}</span><i style={{height:`${Math.max(5,Number(row.encounters)/max*100)}%`}}/><small>{formatDateOnly(row.business_date)}</small></div>)}{!recent.length?<p className="empty-state">No activity in the selected period.</p>:null}</div></section>}
function BedOccupancy({rows}:{rows:Bed[]}){return <section className="occupancy-grid">{rows.map(row=><article className="occupancy-card" key={row.ward_code}><div><strong>{row.ward_name}</strong><span>{row.occupied_beds} occupied · {row.available_beds} available</span></div><b>{Number(row.occupancy_percent||0).toFixed(1)}%</b><i><span style={{width:`${Math.min(100,Number(row.occupancy_percent||0))}%`}}/></i></article>)}</section>}

function ReportTable({tab,rows}:{tab:Tab;rows:Row[]}){
 type Column=[string,string,(value:unknown,row:Row)=>React.ReactNode];
 const configs:Record<Tab,Column[]>={
  operations:[["business_date","Date",v=>String(v)],["encounters","Encounters",v=>number(Number(v))],["opd_visits","OPD",v=>number(Number(v))],["admissions","Admissions",v=>number(Number(v))],["discharges","Discharges",v=>number(Number(v))],["orders","Orders",v=>number(Number(v))],["prescriptions","Rx",v=>number(Number(v))],["charges","Charges",v=>money(Number(v))],["collections","Collections",v=>money(Number(v))]],
  revenue:[["business_date","Date",v=>String(v)],["source_type","Source",v=>label(String(v))],["gross_charges","Gross charges",v=>money(Number(v))],["deductions","Deductions",v=>money(Number(v))],["transaction_count","Transactions",v=>number(Number(v))]],
  balances:[["mrn","MRN",v=>String(v)],["last_name","Patient",(v,row)=>`${v}, ${row.first_name}`],["admission_no","Admission",v=>String(v||"—")],["gross_charges","Gross",v=>money(Number(v))],["approved_deductions","Deductions",v=>money(Number(v))],["payments","Payments",v=>money(Number(v))],["final_balance","Balance",v=>money(Number(v))],["status","Status",v=><span className={`badge ${v==="cleared"?"green":v==="finalized"?"blue":"amber"}`}>{label(String(v))}</span>]],
  disease:[["census_month","Month",v=>String(v)],["code","ICD-10",v=>String(v||"Uncoded")],["description","Diagnosis",v=>String(v)],["disease_class","Class",v=>label(String(v||"Unclassified"))],["classification","Diagnosis type",v=>label(String(v))],["patient_count","Patients",v=>number(Number(v))],["encounter_count","Encounters",v=>number(Number(v))],["reportable","Reportable",v=>v?<span className="badge red">Yes</span>:"No"]],
  inventory:[["store_name","Location",v=>String(v)],["product_code","Code",v=>String(v)],["product_name","Product",v=>String(v)],["quantity_on_hand","On hand",(v,row)=>`${number(Number(v))} ${row.unit}`],["reorder_level","Reorder level",v=>number(Number(v))],["nearest_expiry","Nearest expiry",v=>String(v||"—")],["stock_value","Stock value",v=>money(Number(v))],["risk_status","Status",v=><span className={`badge ${v==="healthy"?"green":v==="low_stock"?"red":"amber"}`}>{label(String(v))}</span>]],
  audit:[["created_at","Date/time",v=>formatDateTime(String(v))],["actor","Actor",v=>String(v)],["event_type","Event",v=>label(String(v))],["object_type","Object",v=>label(String(v||"—"))],["result","Result",v=><span className={`badge ${v==="success"?"green":"red"}`}>{String(v)}</span>],["reason","Reason",v=>String(v||"—")]],
 };
 const columns=configs[tab];return <table className="data-table"><thead><tr>{columns.map(([key,title])=><th key={key}>{title}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.billing_case_id||row.id||row.business_date||row.product_code||`${row.code}-${index}`)} className={index%2?"alternate":""}>{columns.map(([key,,render])=><td key={key}>{render(row[key],row)}</td>)}</tr>)}{!rows.length?<tr><td colSpan={columns.length} className="empty-state">No records found for this report.</td></tr>:null}</tbody></table>;
}
