"use client";

import { useActionState, useMemo, useState } from "react";
import { LockKeyhole, Pencil, Plus, ShieldCheck, ToggleLeft, ToggleRight, X } from "lucide-react";
import { changeRoleStatus, createRole, updateRole, type RoleState } from "@/app/administration/roles/actions";

export type GovernedRole = { id:string;name:string;description:string|null;status:string;version:number;privilege_codes:string[];active_users:number };
export type Privilege = { code:string;description:string;risk_level:string };
const initial: RoleState = { ok:false, message:"" };
const groupLabels:Record<string,string>={admin:"Administration",adt:"Admission and transfer",audit:"Audit",billing:"Billing",cashier:"Cashier",charge_master:"Charge master",clinical:"Consultation",clinical_registry:"Clinical registry",doctors:"Doctors",inventory:"Inventory",medicines:"Medicines",orders:"Orders and results",patients:"Patients",pharmacy:"Pharmacy",queue:"Queue",reference:"Reference data",reports:"Reports",services:"Services"};

export function RolesWorkspace({facilityId,roles,privileges}:{facilityId:string;roles:GovernedRole[];privileges:Privilege[]}){
  const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<GovernedRole|null>(null);const [statusRole,setStatusRole]=useState<GovernedRole|null>(null);
  const privilegeMap=useMemo(()=>new Map(privileges.map(privilege=>[privilege.code,privilege])),[privileges]);
  return <>
    <section className="admin-summary-grid"><article className="metric"><div className="metric-head"><span>Roles</span><ShieldCheck size={18}/></div><strong>{roles.length}</strong><small>{roles.filter(role=>role.status==="active").length} active roles</small></article><article className="metric"><div className="metric-head"><span>Privileges</span><LockKeyhole size={18}/></div><strong>{privileges.length}</strong><small>Server-enforced capability codes</small></article><article className="metric"><div className="metric-head"><span>High-risk grants</span><LockKeyhole size={18}/></div><strong>{privileges.filter(privilege=>privilege.risk_level==="high_risk").length}</strong><small>Require explicit governed assignment</small></article></section>
    <div className="toolbar"><button className="btn btn-primary" onClick={()=>setCreating(true)}><Plus size={15}/>Create role</button></div>
    <section className="card"><div className="card-header"><div><h3>Organization roles</h3><p>Users receive only the privileges granted through active roles at their facility.</p></div><span className="badge blue">Deny by default</span></div><div className="table-wrap"><table className="data-table admin-roles-table"><thead><tr><th>Role</th><th>Assigned users</th><th>Privileges</th><th>Risk profile</th><th>Status</th><th>Actions</th></tr></thead><tbody>
      {roles.map(role=>{const system=role.name==="Hospital Administrator";const grants=role.privilege_codes.map(code=>privilegeMap.get(code)).filter((value):value is Privilege=>Boolean(value));const high=grants.filter(grant=>grant.risk_level==="high_risk").length;return <tr key={role.id}><td className="name-cell"><strong>{role.name}</strong><span>{role.description||"No description"}{system?" · System managed":` · Version ${role.version}`}</span></td><td>{role.active_users}</td><td><strong>{role.privilege_codes.length}</strong></td><td><span className={`badge ${high?"red":"blue"}`}>{high?`${high} high risk`:"Standard"}</span></td><td><span className={`badge ${role.status==="active"?"green":"red"}`}>{role.status}</span></td><td><div className="admin-row-actions"><button className="btn btn-secondary" disabled={system} title={system?"System role grants are synchronized by migrations":"Edit role"} onClick={()=>setEditing(role)}><Pencil size={14}/>Edit</button><button className="btn btn-secondary" disabled={system} title={system?"System role cannot be deactivated":"Change role status"} onClick={()=>setStatusRole(role)}>{role.status==="active"?<ToggleRight size={15}/>:<ToggleLeft size={15}/>} {role.status==="active"?"Deactivate":"Activate"}</button></div></td></tr>})}
      {!roles.length?<tr><td colSpan={6} className="empty-state">No roles are configured for this organization.</td></tr>:null}
    </tbody></table></div></section>
    {creating?<RoleDialog title="Create role" facilityId={facilityId} privileges={privileges} action={createRole} close={()=>setCreating(false)}/>:null}
    {editing?<RoleDialog title={`Edit ${editing.name}`} facilityId={facilityId} role={editing} privileges={privileges} action={updateRole} close={()=>setEditing(null)}/>:null}
    {statusRole?<RoleStatusDialog facilityId={facilityId} role={statusRole} close={()=>setStatusRole(null)}/>:null}
  </>;
}

function ModalHead({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Access governance</p><h3>{title}</h3></div><button type="button" className="icon-btn" onClick={close} aria-label="Close"><X size={17}/></button></div>}

function RoleDialog({title,facilityId,role,privileges,action,close}:{title:string;facilityId:string;role?:GovernedRole;privileges:Privilege[];action:(state:RoleState,form:FormData)=>Promise<RoleState>;close:()=>void}){
  const [state,formAction,pending]=useActionState(action,initial);const selected=new Set(role?.privilege_codes||[]);
  const groups=useMemo(()=>{const grouped=new Map<string,Privilege[]>();for(const privilege of privileges){const prefix=privilege.code.split(".")[0];grouped.set(prefix,[...(grouped.get(prefix)||[]),privilege]);}return [...grouped.entries()];},[privileges]);
  return <div className="modal-backdrop"><section className="modal admin-role-modal" role="dialog" aria-modal="true"><ModalHead title={title} close={close}/><form action={formAction} className="admin-role-form"><input type="hidden" name="facility_id" value={facilityId}/>{role?<><input type="hidden" name="role_id" value={role.id}/><input type="hidden" name="version" value={role.version}/></>:null}<div className="admin-role-details"><label>Role name<input required minLength={3} maxLength={100} name="name" defaultValue={role?.name||""}/></label><label>Description<textarea maxLength={500} rows={3} name="description" defaultValue={role?.description||""}/></label>{role?<label>Reason for modification<textarea required minLength={5} maxLength={500} rows={3} name="reason"/></label>:null}</div><div className="privilege-matrix"><div className="privilege-matrix-head"><strong>Privilege grants</strong><span>{privileges.length} available capabilities</span></div>{groups.map(([prefix,items])=><fieldset key={prefix}><legend>{groupLabels[prefix]||prefix}</legend>{items.map(privilege=><label key={privilege.code}><input type="checkbox" name="privilege_codes" value={privilege.code} defaultChecked={selected.has(privilege.code)}/><span><strong>{privilege.code}</strong><small>{privilege.description}</small></span><b className={`badge ${privilege.risk_level==="high_risk"?"red":privilege.risk_level==="privileged"?"amber":"blue"}`}>{privilege.risk_level.replace("_"," ")}</b></label>)}</fieldset>)}</div>{state.message?<div className={state.ok?"form-success":"form-error"} aria-live="polite">{state.message}</div>:null}<div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>{state.ok?"Close":"Cancel"}</button>{!state.ok?<button disabled={pending} className="btn btn-primary">{pending?"Saving…":role?"Save role":"Create role"}</button>:null}</div></form></section></div>;
}

function RoleStatusDialog({facilityId,role,close}:{facilityId:string;role:GovernedRole;close:()=>void}){const[state,action,pending]=useActionState(changeRoleStatus,initial);const next=role.status==="active"?"inactive":"active";return <div className="modal-backdrop"><section className="modal admin-status-modal" role="dialog" aria-modal="true"><ModalHead title={`${next==="active"?"Activate":"Deactivate"} ${role.name}`} close={close}/><form action={action} className="adt-dialog-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="role_id" value={role.id}/><input type="hidden" name="status" value={next}/><p>{next==="inactive"?"A role can be deactivated only after all active staff assignments are removed or replaced.":"The role can be assigned to facility staff again."}</p><label>Reason<textarea required minLength={5} maxLength={500} rows={5} name="reason"/></label>{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button>{!state.ok?<button disabled={pending} className="btn btn-primary">{pending?"Saving…":"Confirm status"}</button>:null}</div></form></section></div>}
