"use client";

import { useActionState, useMemo, useState } from "react";
import { Bell, FileText, Hash, Pencil, Plus, ToggleLeft, ToggleRight, X } from "lucide-react";
import { changeTemplateStatus, saveSetting, saveTemplate, type SettingsState } from "@/app/administration/templates-settings/actions";

export type TemplateRow={id:string;code:string;name:string;category:string;description:string|null;content:string;status:string;version:number};
export type SettingRow={id:string;setting_key:string;category:string;label:string;setting_value:string;description:string|null;version:number;updated_at:string};
const initial:SettingsState={ok:false,message:""};

export function TemplatesSettingsWorkspace({facilityId,templates,settings}:{facilityId:string;templates:TemplateRow[];settings:SettingRow[]}){
 const[tab,setTab]=useState<"templates"|"settings">("templates");const[template,setTemplate]=useState<TemplateRow|null|undefined>();const[statusTemplate,setStatusTemplate]=useState<TemplateRow|null>(null);const[setting,setSetting]=useState<SettingRow|null>(null);const[category,setCategory]=useState("all");
 const visibleTemplates=useMemo(()=>category==="all"?templates:templates.filter(row=>row.category===category),[templates,category]);
 return <>
  <section className="admin-summary-grid"><Metric label="Templates" value={templates.length} note={`${templates.filter(row=>row.status==="active").length} active`} icon={<FileText size={18}/>}/><Metric label="Numbering rules" value={settings.filter(row=>row.category==="numbering").length} note="Facility-scoped prefixes" icon={<Hash size={18}/>}/><Metric label="Notifications" value={settings.filter(row=>row.category==="notification").length} note="Operational alert controls" icon={<Bell size={18}/>}/></section>
  <div className="master-tabs"><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}>Templates</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>Facility settings</button></div>
  {tab==="templates"?<><div className="toolbar"><button className="btn btn-primary" onClick={()=>setTemplate(null)}><Plus size={14}/>Add template</button><select className="filter" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">All categories</option><option value="clinical">Clinical</option><option value="administrative">Administrative</option><option value="billing">Billing</option><option value="notification">Notification</option></select></div><section className="card"><div className="card-header"><div><h3>Reusable templates</h3><p>Versioned content for clinical, administrative, billing, and notification workflows.</p></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Template</th><th>Category</th><th>Preview</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleTemplates.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.name}</strong><span>{row.code} · Version {row.version}</span></td><td><span className="badge blue">{row.category}</span></td><td className="template-preview">{row.content.slice(0,110)}{row.content.length>110?"…":""}</td><td><span className={`badge ${row.status==="active"?"green":"red"}`}>{row.status}</span></td><td><div className="admin-row-actions"><button className="btn btn-secondary" onClick={()=>setTemplate(row)}><Pencil size={13}/>Edit</button><button className="btn btn-secondary" onClick={()=>setStatusTemplate(row)}>{row.status==="active"?<ToggleRight size={14}/>:<ToggleLeft size={14}/>}</button></div></td></tr>)}{!visibleTemplates.length?<tr><td colSpan={5} className="empty-state">No templates match this category.</td></tr>:null}</tbody></table></div></section></>:<section className="settings-grid">{settings.map(row=><article className="card setting-card" key={row.id}><div><span className="badge blue">{row.category}</span><h3>{row.label}</h3><code>{row.setting_key}</code><p>{row.description||"Facility-controlled operational setting."}</p></div><div className="setting-card-value"><strong>{row.setting_value}</strong><button className="btn btn-secondary" onClick={()=>setSetting(row)}><Pencil size={13}/>Edit</button></div></article>)}{!settings.length?<div className="empty-state">No facility settings configured.</div>:null}</section>}
  {template!==undefined?<TemplateDialog facilityId={facilityId} row={template||undefined} close={()=>setTemplate(undefined)}/>:null}
  {statusTemplate?<TemplateStatusDialog facilityId={facilityId} row={statusTemplate} close={()=>setStatusTemplate(null)}/>:null}
  {setting?<SettingDialog facilityId={facilityId} row={setting} close={()=>setSetting(null)}/>:null}
 </>;
}

function Metric({label,value,note,icon}:{label:string;value:number;note:string;icon:React.ReactNode}){return <article className="metric"><div className="metric-head"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{note}</small></article>}
function Head({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Templates and settings</p><h3>{title}</h3></div><button type="button" className="icon-btn" onClick={close} aria-label="Close"><X size={17}/></button></div>}
function TemplateDialog({facilityId,row,close}:{facilityId:string;row?:TemplateRow;close:()=>void}){const[state,action,pending]=useActionState(saveTemplate,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={row?`Edit ${row.name}`:"Add template"} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="template_id" value={row?.id||""}/><input type="hidden" name="version" value={row?.version||0}/><label>Code<input name="code" required readOnly={Boolean(row)} defaultValue={row?.code||""}/></label><label>Name<input name="name" required defaultValue={row?.name||""}/></label><label>Category<select name="category" defaultValue={row?.category||"clinical"}><option value="clinical">Clinical</option><option value="administrative">Administrative</option><option value="billing">Billing</option><option value="notification">Notification</option></select></label><label>Description<input name="description" defaultValue={row?.description||""}/></label><label className="wide">Template content<textarea name="content" required rows={10} defaultValue={row?.content||""}/></label>{row?<label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={2}/></label>:null}{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function TemplateStatusDialog({facilityId,row,close}:{facilityId:string;row:TemplateRow;close:()=>void}){const[state,action,pending]=useActionState(changeTemplateStatus,initial);const next=row.status==="active"?"inactive":"active";return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={`${next==="active"?"Activate":"Deactivate"} ${row.name}`} close={close}/><form action={action} className="adt-dialog-form"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="template_id" value={row.id}/><input type="hidden" name="status" value={next}/><label>Reason<textarea name="reason" required minLength={5} rows={4}/></label>{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function SettingDialog({facilityId,row,close}:{facilityId:string;row:SettingRow;close:()=>void}){const[state,action,pending]=useActionState(saveSetting,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={`Edit ${row.label}`} close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><input type="hidden" name="setting_id" value={row.id}/><input type="hidden" name="version" value={row.version}/><label className="wide">Setting key<input readOnly value={row.setting_key}/></label><label>Label<input name="label" required defaultValue={row.label}/></label><label>Value<input name="setting_value" required defaultValue={row.setting_value}/></label><label className="wide">Reason for modification<textarea name="reason" required minLength={5} rows={3}/></label>{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<Actions pending={pending} ok={state.ok} close={close}/></form></section></div>}
function Actions({pending,ok,close}:{pending:boolean;ok:boolean;close:()=>void}){return <div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>{ok?"Close":"Cancel"}</button>{!ok?<button className="btn btn-primary" disabled={pending}>{pending?"Saving…":"Save"}</button>:null}</div>}
