"use client";

import { useActionState, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Plus, ShieldCheck, X, XCircle } from "lucide-react";
import { decideWorkflowRequest, submitWorkflowRequest, type WorkflowState } from "@/app/administration/workflow-approvals/actions";

export type WorkflowRequest={id:string;request_type:string;subject:string;object_type:string|null;object_id:string|null;request_details:string|null;reason:string;status:string;requested_by:string;requested_at:string;decided_by:string|null;decided_at:string|null;decision_reason:string|null;version:number;requester?:{full_name:string;employee_no:string|null}|null;decider?:{full_name:string;employee_no:string|null}|null};
const initial:WorkflowState={ok:false,message:""};
const labels:Record<string,string>={patient_merge:"Patient merge",discount:"Discount",void:"Void",refund:"Refund",publication:"Publication"};

export function WorkflowApprovalsWorkspace({facilityId,requests}:{facilityId:string;requests:WorkflowRequest[]}){
 const[creating,setCreating]=useState(false);const[deciding,setDeciding]=useState<WorkflowRequest|null>(null);const[filter,setFilter]=useState("all");
 const visible=useMemo(()=>filter==="all"?requests:requests.filter(row=>row.status===filter),[requests,filter]);
 return <>
  <section className="admin-summary-grid"><Metric label="Pending" value={requests.filter(row=>row.status==="pending").length} note="Awaiting governed decision" icon={<Clock3 size={18}/>}/><Metric label="Approved" value={requests.filter(row=>row.status==="approved").length} note="Approved requests" icon={<CheckCircle2 size={18}/>}/><Metric label="Rejected" value={requests.filter(row=>row.status==="rejected").length} note="Rejected requests" icon={<XCircle size={18}/>}/></section>
  <div className="toolbar"><button className="btn btn-primary" onClick={()=>setCreating(true)}><Plus size={14}/>New request</button><select className="filter" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select></div>
  <section className="card"><div className="card-header"><div><h3>Governed approval queue</h3><p>Merge, discount, void, refund, and publication decisions with complete accountability.</p></div><span className="badge blue">Audited</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Type</th><th>Requested by</th><th>Reason</th><th>Status</th><th>Decision</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td className="name-cell"><strong>{row.subject}</strong><span>{new Date(row.requested_at).toLocaleString("en-PH",{timeZone:"Asia/Manila"})}{row.object_type?` · ${row.object_type}`:""}</span></td><td><span className="badge blue">{labels[row.request_type]||row.request_type}</span></td><td>{row.requester?.full_name||"Unknown"}<span className="cell-muted">{row.requester?.employee_no?` · ${row.requester.employee_no}`:""}</span></td><td className="workflow-reason-cell">{row.reason}</td><td><span className={`badge ${row.status==="approved"?"green":row.status==="pending"?"amber":"red"}`}>{row.status}</span></td><td>{row.status==="pending"?<button className="btn btn-secondary" onClick={()=>setDeciding(row)}><ShieldCheck size={13}/>Review</button>:<span className="cell-muted">{row.decider?.full_name||"Decision recorded"}{row.decision_reason?` · ${row.decision_reason}`:""}</span>}</td></tr>)}{!visible.length?<tr><td colSpan={6} className="empty-state">No workflow requests match this filter.</td></tr>:null}</tbody></table></div></section>
  {creating?<RequestDialog facilityId={facilityId} close={()=>setCreating(false)}/>:null}
  {deciding?<DecisionDialog row={deciding} close={()=>setDeciding(null)}/>:null}
 </>;
}

function Metric({label,value,note,icon}:{label:string;value:number;note:string;icon:React.ReactNode}){return <article className="metric"><div className="metric-head"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{note}</small></article>}
function Head({title,close}:{title:string;close:()=>void}){return <div className="modal-head"><div><p className="eyebrow">Workflow governance</p><h3>{title}</h3></div><button type="button" className="icon-btn" onClick={close} aria-label="Close"><X size={17}/></button></div>}
function RequestDialog({facilityId,close}:{facilityId:string;close:()=>void}){const[state,action,pending]=useActionState(submitWorkflowRequest,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title="Submit approval request" close={close}/><form action={action} className="admin-form-grid"><input type="hidden" name="facility_id" value={facilityId}/><label>Request type<select name="request_type" required defaultValue="discount">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Subject<input name="subject" required minLength={3} placeholder="Short, specific request title"/></label><label>Related record type<input name="object_type" placeholder="Example: patient, ledger_entry, report"/></label><label>Related record ID<input name="object_id" placeholder="Optional UUID" pattern="[0-9a-fA-F-]{36}"/></label><label className="wide">Request details<textarea name="details" rows={5} placeholder="What action should be performed after approval?"/></label><label className="wide">Business reason<textarea name="reason" required minLength={5} rows={3}/></label>{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>{state.ok?"Close":"Cancel"}</button>{!state.ok?<button className="btn btn-primary" disabled={pending}>{pending?"Submitting…":"Submit request"}</button>:null}</div></form></section></div>}
function DecisionDialog({row,close}:{row:WorkflowRequest;close:()=>void}){const[state,action,pending]=useActionState(decideWorkflowRequest,initial);return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><Head title={`Review ${row.subject}`} close={close}/><form action={action} className="adt-dialog-form"><input type="hidden" name="request_id" value={row.id}/><input type="hidden" name="version" value={row.version}/><div className="approval-review"><span>Type</span><strong>{labels[row.request_type]||row.request_type}</strong><span>Requested reason</span><p>{row.reason}</p><span>Details</span><p>{row.request_details||"No additional details."}</p></div><label>Decision<select name="decision" required defaultValue=""><option value="">Select decision</option><option value="approved">Approve</option><option value="rejected">Reject</option></select></label><label>Decision reason<textarea name="reason" required minLength={5} rows={4}/></label>{state.message?<div className={state.ok?"form-success":"form-error"}>{state.message}</div>:null}<div className="form-actions"><button type="button" className="btn btn-secondary" onClick={close}>{state.ok?"Close":"Cancel"}</button>{!state.ok?<button className="btn btn-primary" disabled={pending}>{pending?"Recording…":"Record decision"}</button>:null}</div></form></section></div>}
