import { redirect } from "next/navigation";
import { PageHeading } from "@/components/app-shell";
import { ClinicalRegistryWorkspace } from "@/components/clinical-registry-workspace";
import { createClient } from "@/lib/supabase/server";

export default async function ClinicalRegistryPage(){
 const supabase=await createClient();const{data:claims}=await supabase.auth.getClaims();const userId=claims?.claims.sub;if(!userId)redirect("/login");
 const{data:roles}=await supabase.from("user_roles").select("facility_id,facilities(organization_id)").eq("user_id",userId).eq("active",true).limit(1);const role=roles?.[0],facilityId=role?.facility_id,facilityRelation=role?.facilities,organizationId=(Array.isArray(facilityRelation)?facilityRelation[0]:facilityRelation)?.organization_id;if(!facilityId||!organizationId)return <div className="form-error">No active facility assignment.</div>;
 const[{data:catalog},{data:encounters},{data:doctorRows},{data:fees},{data:census}]=await Promise.all([
  supabase.from("diagnosis_catalog").select("id,code_system,code,title,chapter,category,disease_class,clinical_course,reportable,philhealth_case_rate_code,source_version,status,version").eq("organization_id",organizationId).order("code").limit(1000),
  supabase.from("encounters").select("id,encounter_no,encounter_type,status,service_date,patient_id,patients(id,mrn,first_name,last_name,birth_date,sex_at_birth),diagnoses(id,encounter_id,diagnosis_catalog_id,code_system,code,description,classification,verification_status,clinical_status,present_on_admission,is_comorbidity,is_complication,onset_date,resolved_at,version,created_at),encounter_care_team(id,encounter_id,doctor_id,role,is_primary,assigned_from,assigned_to,fee_schedule_id,professional_fee,fee_status,billing_ledger_entry_id,status,notes,version),vital_observations(encounter_id,code,value,unit,observed_at)").eq("facility_id",facilityId).order("service_date",{ascending:false}).limit(200),
  supabase.from("doctor_facility_assignments").select("doctor_id,doctors(id,first_name,last_name,suffix,specialty,status)").eq("facility_id",facilityId).eq("active",true),
  supabase.from("doctor_fee_schedules").select("id,doctor_id,service_id,encounter_type,room_type,standard_amount,active").eq("facility_id",facilityId).eq("active",true).limit(500),
  supabase.from("disease_census").select("census_month,encounter_type,code,description,chapter,category,disease_class,clinical_course,reportable,classification,verification_status,encounter_count,patient_count,male_patients,female_patients").eq("facility_id",facilityId).order("census_month",{ascending:false}).limit(500)
 ]);
 const diagnoses=(encounters||[]).flatMap(item=>item.diagnoses||[]).sort((left,right)=>new Date(right.created_at).getTime()-new Date(left.created_at).getTime()),assignments=(encounters||[]).flatMap(item=>item.encounter_care_team||[]).sort((left,right)=>new Date(right.assigned_from).getTime()-new Date(left.assigned_from).getTime()),patients=[...new Map((encounters||[]).flatMap(item=>{const relation=item.patients,patient=Array.isArray(relation)?relation[0]:relation;return patient?[[patient.id,patient] as const]:[]})).values()],vitals=(encounters||[]).flatMap(item=>item.vital_observations||[]).sort((left,right)=>new Date(right.observed_at).getTime()-new Date(left.observed_at).getTime()).slice(0,1000),encounterRows=(encounters||[]).map(item=>({id:item.id,encounter_no:item.encounter_no,encounter_type:item.encounter_type,status:item.status,service_date:item.service_date,patient_id:item.patient_id}));
 const doctors=(doctorRows||[]).flatMap(row=>{const doctor=Array.isArray(row.doctors)?row.doctors[0]:row.doctors;return doctor&&doctor.status==="active"?[doctor]:[]});
 return <><PageHeading eyebrow="Clinical intelligence foundation" title="Diagnosis, care team, and disease registry" description="Maintain structured diagnoses, multiple doctors per encounter, patient timelines, and hospital disease classifications—the governed data foundation for future AI assistance."/><ClinicalRegistryWorkspace facilityId={facilityId} catalog={catalog||[]} encounters={encounterRows} diagnoses={diagnoses} assignments={assignments} patients={patients} doctors={doctors} fees={fees||[]} vitals={vitals} census={census||[]}/></>;
}
