begin;
create extension if not exists pgcrypto;
create type public.record_status as enum('draft','active','inactive','retired');
create type public.encounter_status as enum('planned','arrived','triaged','in_consultation','awaiting_service','for_billing','completed','cancelled');
create type public.appointment_status as enum('draft','scheduled','confirmed','arrived','in_queue','in_service','completed','cancelled','no_show');
create type public.ledger_kind as enum('charge','discount','payment','refund','reversal','adjustment');

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,code text not null unique,status public.record_status not null default 'active',created_at timestamptz not null default now());
create table public.facilities(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,code text not null,name text not null,level text not null default 'Level 1',timezone text not null default 'Asia/Manila',status public.record_status not null default 'active',created_at timestamptz not null default now(),unique(organization_id,code));
create table public.departments(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,code text not null,name text not null,status public.record_status not null default 'active',unique(facility_id,code));
create table public.profiles(id uuid primary key references auth.users on delete restrict,full_name text not null,employee_no text,status public.record_status not null default 'active',created_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null,description text,unique(organization_id,name));
create table public.privileges(code text primary key,description text not null,risk_level text not null default 'normal' check(risk_level in('normal','privileged','high_risk')));
create table public.role_privileges(role_id uuid references public.roles on delete cascade,privilege_code text references public.privileges on delete cascade,primary key(role_id,privilege_code));
create table public.user_roles(user_id uuid references public.profiles on delete cascade,role_id uuid references public.roles on delete cascade,facility_id uuid references public.facilities on delete cascade,department_id uuid references public.departments on delete cascade,active boolean not null default true,primary key(user_id,role_id,facility_id));

create table public.patients(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,mrn text not null,first_name text not null,middle_name text,last_name text not null,suffix text,birth_date date,estimated_age integer,sex_at_birth text,phone text,email text,address jsonb not null default '{}',deceased_at timestamptz,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,unique(organization_id,mrn));
create index patients_search_idx on public.patients(organization_id,last_name,first_name,birth_date);
create table public.patient_identifiers(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients,type text not null,value text not null,issuer text,unique(patient_id,type,value));
create table public.patient_consents(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients,type text not null,status text not null,recorded_by uuid not null references public.profiles,recorded_at timestamptz not null default now(),evidence_path text);
create table public.patient_merge_requests(id uuid primary key default gen_random_uuid(),source_patient_id uuid not null references public.patients,target_patient_id uuid not null references public.patients,reason text not null,status text not null default 'requested',requested_by uuid not null references public.profiles,approved_by uuid references public.profiles,created_at timestamptz not null default now(),check(source_patient_id<>target_patient_id));

create table public.appointments(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,department_id uuid not null references public.departments,patient_id uuid not null references public.patients,scheduled_at timestamptz,status public.appointment_status not null default 'draft',priority text not null default 'routine',reason text,created_by uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.encounters(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,department_id uuid not null references public.departments,patient_id uuid not null references public.patients,appointment_id uuid references public.appointments,encounter_no text not null,encounter_type text not null default 'OPD',status public.encounter_status not null default 'planned',responsible_provider_id uuid references public.profiles,service_date date not null default current_date,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),unique(facility_id,encounter_no));
create table public.queue_entries(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,department_id uuid not null references public.departments,queue_no text not null,status text not null default 'waiting',priority integer not null default 0,arrived_at timestamptz not null default now(),called_at timestamptz,service_started_at timestamptz,completed_at timestamptz);
create table public.vital_observations(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,code text not null,value numeric not null,unit text not null,observed_by uuid not null references public.profiles,observed_at timestamptz not null default now());
create table public.allergies(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients,substance text not null,reaction text,severity text,status text not null default 'active',recorded_by uuid not null references public.profiles,recorded_at timestamptz not null default now());
create table public.clinical_notes(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,note_type text not null,status text not null default 'draft',current_version integer not null default 1,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),finalized_at timestamptz);
create table public.clinical_note_versions(id uuid primary key default gen_random_uuid(),note_id uuid not null references public.clinical_notes,version integer not null,content jsonb not null,amendment_reason text,author_id uuid not null references public.profiles,created_at timestamptz not null default now(),unique(note_id,version));
create table public.diagnoses(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,code_system text,code text,description text not null,diagnosis_type text not null default 'working',recorded_by uuid not null references public.profiles,created_at timestamptz not null default now());

create table public.service_catalog(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,code text not null,name text not null,category text not null,billable boolean not null default true,status public.record_status not null default 'active',unique(organization_id,code));
create table public.service_prices(id uuid primary key default gen_random_uuid(),service_id uuid not null references public.service_catalog,facility_id uuid not null references public.facilities,amount numeric(14,2) not null check(amount>=0),effective_from date not null,effective_to date,approved_by uuid references public.profiles,check(effective_to is null or effective_to>=effective_from));
create table public.patient_accounts(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients,facility_id uuid not null references public.facilities,status text not null default 'open',created_at timestamptz not null default now());
create table public.ledger_entries(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.patient_accounts,encounter_id uuid references public.encounters,kind public.ledger_kind not null,source_type text not null,source_id uuid,idempotency_key text unique,description text not null,amount numeric(14,2) not null,currency char(3) not null default 'PHP',reverses_entry_id uuid references public.ledger_entries,posted_by uuid not null references public.profiles,posted_at timestamptz not null default now(),reason text);
create table public.cashier_shifts(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,cashier_id uuid not null references public.profiles,opened_at timestamptz not null default now(),opening_amount numeric(14,2) not null default 0,closed_at timestamptz,expected_amount numeric(14,2),actual_amount numeric(14,2),status text not null default 'open');
create table public.payments(id uuid primary key default gen_random_uuid(),shift_id uuid not null references public.cashier_shifts,account_id uuid not null references public.patient_accounts,receipt_no text not null,payment_method text not null,amount numeric(14,2) not null check(amount>0),status text not null default 'posted',external_reference text,posted_by uuid not null references public.profiles,posted_at timestamptz not null default now(),unique(shift_id,receipt_no));
create table public.payment_allocations(payment_id uuid references public.payments on delete restrict,ledger_entry_id uuid references public.ledger_entries on delete restrict,amount numeric(14,2) not null check(amount>0),primary key(payment_id,ledger_entry_id));

create table public.audit_events(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations,facility_id uuid references public.facilities,actor_id uuid references auth.users,event_type text not null,object_type text,object_id uuid,result text not null default 'success',reason text,details jsonb not null default '{}',correlation_id uuid not null default gen_random_uuid(),created_at timestamptz not null default now());
create index audit_events_scope_time on public.audit_events(organization_id,facility_id,created_at desc);

create or replace function public.user_has_facility(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.user_roles ur join public.profiles p on p.id=ur.user_id where ur.user_id=auth.uid() and ur.facility_id=target and ur.active and p.status='active')$$;
alter table public.organizations enable row level security;alter table public.facilities enable row level security;alter table public.departments enable row level security;alter table public.profiles enable row level security;alter table public.user_roles enable row level security;alter table public.patients enable row level security;alter table public.appointments enable row level security;alter table public.encounters enable row level security;alter table public.queue_entries enable row level security;alter table public.patient_accounts enable row level security;alter table public.ledger_entries enable row level security;alter table public.cashier_shifts enable row level security;alter table public.payments enable row level security;alter table public.audit_events enable row level security;
create policy "users read own profile" on public.profiles for select using(id=auth.uid());
create policy "assigned facility read" on public.facilities for select using(public.user_has_facility(id));
create policy "assigned department read" on public.departments for select using(public.user_has_facility(facility_id));
create policy "assigned patient read" on public.patients for select using(exists(select 1 from public.facilities f where f.organization_id=patients.organization_id and public.user_has_facility(f.id)));
create policy "assigned appointment read" on public.appointments for select using(public.user_has_facility(facility_id));
create policy "assigned encounter read" on public.encounters for select using(public.user_has_facility(facility_id));
create policy "assigned account read" on public.patient_accounts for select using(public.user_has_facility(facility_id));
create policy "assigned shift read" on public.cashier_shifts for select using(public.user_has_facility(facility_id));
-- Mutations are intentionally denied to direct browser table access. Add privilege-aware RPC functions per vertical slice.
-- Audit events have no update or delete policy and must be inserted by trusted server functions.
commit;
