begin;
insert into public.privileges(code,description,risk_level) values ('adt.read','View admissions and bed occupancy','privileged'),('adt.write','Admit, transfer, and discharge patients','high_risk') on conflict(code) do update set description=excluded.description,risk_level=excluded.risk_level;
insert into public.role_privileges(role_id,privilege_code) select r.id,p.code from public.roles r join public.organizations o on o.id=r.organization_id cross join public.privileges p where o.code='INF' and r.name='Hospital Administrator' and p.code in('adt.read','adt.write') on conflict do nothing;
insert into public.wards(facility_id,code,name) select id,'OBS','Observation Ward' from public.facilities where code='PILOT' on conflict(facility_id,code) do update set name=excluded.name;
insert into public.wards(facility_id,code,name) select id,'WARD-A','Ward A' from public.facilities where code='PILOT' on conflict(facility_id,code) do update set name=excluded.name;
insert into public.beds(ward_id,code) select w.id,v.code from public.wards w cross join(values('OBS-01'),('OBS-02'),('OBS-03'))v(code) where w.code='OBS' on conflict(ward_id,code) do nothing;
insert into public.beds(ward_id,code) select w.id,v.code from public.wards w cross join(values('A-01'),('A-02'),('A-03'),('A-04'))v(code) where w.code='WARD-A' on conflict(ward_id,code) do nothing;
create sequence if not exists public.admission_no_seq;
create policy "assigned bed read" on public.beds for select using(exists(select 1 from public.wards w where w.id=beds.ward_id and public.has_privilege('adt.read',w.facility_id)));
create policy "assigned admission read" on public.admissions for select using(exists(select 1 from public.encounters e where e.id=admissions.encounter_id and public.has_privilege('adt.read',e.facility_id)));
create policy "assigned bed stay read" on public.bed_stays for select using(exists(select 1 from public.admissions a join public.encounters e on e.id=a.encounter_id where a.id=bed_stays.admission_id and public.has_privilege('adt.read',e.facility_id)));
create or replace function public.admit_patient(target_facility uuid,target_patient uuid,target_bed uuid) returns uuid language plpgsql security definer set search_path='' as $$declare dept uuid;enc uuid;adm uuid;org uuid;adm_no text;begin
 if auth.uid() is null or not public.has_privilege('adt.write',target_facility) then raise exception 'Not authorized to admit patients';end if;
 select f.organization_id into org from public.facilities f join public.patients p on p.organization_id=f.organization_id where f.id=target_facility and p.id=target_patient;
 if org is null then raise exception 'Patient is outside this facility';end if;
 if not exists(select 1 from public.beds b join public.wards w on w.id=b.ward_id where b.id=target_bed and w.facility_id=target_facility and b.status='available') then raise exception 'Bed is no longer available';end if;
 select id into dept from public.departments where facility_id=target_facility order by code limit 1;
 insert into public.encounters(facility_id,department_id,patient_id,encounter_no,encounter_type,status,created_by) values(target_facility,dept,target_patient,'IPD-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.encounter_no_seq')::text,6,'0'),'IPD','in_consultation',auth.uid()) returning id into enc;
 adm_no:='ADM-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.admission_no_seq')::text,6,'0');
 insert into public.admissions(encounter_id,admission_no,admitted_at,admitted_by) values(enc,adm_no,now(),auth.uid()) returning id into adm;
 insert into public.bed_stays(admission_id,bed_id,started_at,recorded_by) values(adm,target_bed,now(),auth.uid());update public.beds set status='occupied' where id=target_bed;
 insert into public.audit_events(organization_id,facility_id,actor_id,event_type,object_type,object_id,details) values(org,target_facility,auth.uid(),'patient.admitted','admission',adm,jsonb_build_object('admission_no',adm_no,'bed_id',target_bed));return adm;end$$;
create or replace function public.transfer_patient(target_admission uuid,target_bed uuid,transfer_reason text) returns void language plpgsql security definer set search_path='' as $$declare fac uuid;old_bed uuid;org uuid;begin
 select e.facility_id,p.organization_id into fac,org from public.admissions a join public.encounters e on e.id=a.encounter_id join public.patients p on p.id=e.patient_id where a.id=target_admission and a.status in('admitted','for_transfer');
 if fac is null or not public.has_privilege('adt.write',fac) then raise exception 'Not authorized to transfer this admission';end if;
 if not exists(select 1 from public.beds b join public.wards w on w.id=b.ward_id where b.id=target_bed and w.facility_id=fac and b.status='available') then raise exception 'Destination bed is unavailable';end if;
 select bed_id into old_bed from public.bed_stays where admission_id=target_admission and ended_at is null for update;update public.bed_stays set ended_at=now(),transfer_reason=nullif(trim(transfer_reason),'') where admission_id=target_admission and ended_at is null;update public.beds set status='available' where id=old_bed;insert into public.bed_stays(admission_id,bed_id,started_at,transfer_reason,recorded_by) values(target_admission,target_bed,now(),nullif(trim(transfer_reason),''),auth.uid());update public.beds set status='occupied' where id=target_bed;update public.admissions set status='admitted' where id=target_admission;insert into public.audit_events(organization_id,facility_id,actor_id,event_type,object_type,object_id,details) values(org,fac,auth.uid(),'patient.transferred','admission',target_admission,jsonb_build_object('from_bed',old_bed,'to_bed',target_bed));end$$;
create or replace function public.discharge_patient(target_admission uuid,disposition text) returns void language plpgsql security definer set search_path='' as $$declare fac uuid;old_bed uuid;org uuid;enc uuid;begin
 select e.facility_id,p.organization_id,e.id into fac,org,enc from public.admissions a join public.encounters e on e.id=a.encounter_id join public.patients p on p.id=e.patient_id where a.id=target_admission and a.status<>'discharged';if fac is null or not public.has_privilege('adt.write',fac) then raise exception 'Not authorized to discharge this admission';end if;
 select bed_id into old_bed from public.bed_stays where admission_id=target_admission and ended_at is null for update;update public.bed_stays set ended_at=now() where admission_id=target_admission and ended_at is null;update public.beds set status='cleaning' where id=old_bed;update public.admissions set status='discharged',discharged_at=now(),discharge_disposition=trim(disposition) where id=target_admission;update public.encounters set status='completed' where id=enc;insert into public.audit_events(organization_id,facility_id,actor_id,event_type,object_type,object_id,details) values(org,fac,auth.uid(),'patient.discharged','admission',target_admission,jsonb_build_object('disposition',trim(disposition)));end$$;
grant execute on function public.admit_patient(uuid,uuid,uuid) to authenticated;grant execute on function public.transfer_patient(uuid,uuid,text) to authenticated;grant execute on function public.discharge_patient(uuid,text) to authenticated;
commit;
