begin;

create table public.wards(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,code text not null,name text not null,status public.record_status not null default 'active',unique(facility_id,code));
create table public.beds(id uuid primary key default gen_random_uuid(),ward_id uuid not null references public.wards,code text not null,status text not null default 'available' check(status in('available','occupied','reserved','cleaning','maintenance','inactive')),unique(ward_id,code));
create table public.admissions(id uuid primary key default gen_random_uuid(),encounter_id uuid not null unique references public.encounters,admission_no text not null,admitted_at timestamptz not null,admitted_by uuid not null references public.profiles,status text not null default 'admitted' check(status in('planned','admitted','for_transfer','for_discharge','discharged','cancelled')),discharged_at timestamptz,discharge_disposition text,unique(admission_no));
create table public.bed_stays(id uuid primary key default gen_random_uuid(),admission_id uuid not null references public.admissions,bed_id uuid not null references public.beds,started_at timestamptz not null,ended_at timestamptz,transfer_reason text,recorded_by uuid not null references public.profiles,check(ended_at is null or ended_at>=started_at));
create unique index one_active_stay_per_admission on public.bed_stays(admission_id) where ended_at is null;
create unique index one_active_patient_per_bed on public.bed_stays(bed_id) where ended_at is null;

create table public.clinical_orders(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,order_no text not null,order_type text not null,priority text not null default 'routine',status text not null default 'requested' check(status in('requested','acknowledged','collected','in_progress','completed','validated','released','cancelled')),ordered_by uuid not null references public.profiles,ordered_at timestamptz not null default now(),instructions text,unique(order_no));
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.clinical_orders,service_id uuid references public.service_catalog,description text not null,status text not null default 'requested',charge_on text not null default 'completion' check(charge_on in('request','collection','completion','release','none')));
create table public.clinical_results(id uuid primary key default gen_random_uuid(),order_item_id uuid not null references public.order_items,result_data jsonb not null,result_text text,status text not null default 'draft' check(status in('draft','final','corrected')),entered_by uuid not null references public.profiles,entered_at timestamptz not null default now(),validated_by uuid references public.profiles,validated_at timestamptz,correction_reason text);

create table public.stores(id uuid primary key default gen_random_uuid(),facility_id uuid not null references public.facilities,code text not null,name text not null,store_type text not null default 'supply',unique(facility_id,code));
create table public.products(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,code text not null,name text not null,product_type text not null check(product_type in('medicine','supply')),unit text not null,reorder_level numeric(14,3) not null default 0,status public.record_status not null default 'active',unique(organization_id,code));
create table public.stock_lots(id uuid primary key default gen_random_uuid(),store_id uuid not null references public.stores,product_id uuid not null references public.products,lot_no text not null,expiry_date date,quantity_on_hand numeric(14,3) not null default 0 check(quantity_on_hand>=0),unit_cost numeric(14,2) not null default 0,unique(store_id,product_id,lot_no));
create table public.stock_movements(id uuid primary key default gen_random_uuid(),store_id uuid not null references public.stores,product_id uuid not null references public.products,lot_id uuid references public.stock_lots,movement_type text not null check(movement_type in('receipt','issue','transfer_in','transfer_out','dispense','return','adjustment')),quantity numeric(14,3) not null check(quantity<>0),source_type text not null,source_id uuid,reason text,posted_by uuid not null references public.profiles,posted_at timestamptz not null default now(),idempotency_key text unique);
create table public.prescriptions(id uuid primary key default gen_random_uuid(),encounter_id uuid not null references public.encounters,prescription_no text not null unique,status text not null default 'draft' check(status in('draft','ordered','validated','partially_dispensed','dispensed','cancelled')),prescribed_by uuid not null references public.profiles,prescribed_at timestamptz not null default now());
create table public.prescription_items(id uuid primary key default gen_random_uuid(),prescription_id uuid not null references public.prescriptions,product_id uuid not null references public.products,dose text not null,route text,frequency text,duration text,quantity numeric(14,3) not null check(quantity>0),instructions text);
create table public.dispenses(id uuid primary key default gen_random_uuid(),prescription_item_id uuid not null references public.prescription_items,stock_lot_id uuid not null references public.stock_lots,quantity numeric(14,3) not null check(quantity>0),status text not null default 'posted' check(status in('posted','returned','reversed')),dispensed_by uuid not null references public.profiles,dispensed_at timestamptz not null default now(),ledger_entry_id uuid references public.ledger_entries,idempotency_key text unique);

alter table public.wards enable row level security;alter table public.beds enable row level security;alter table public.admissions enable row level security;alter table public.bed_stays enable row level security;alter table public.clinical_orders enable row level security;alter table public.order_items enable row level security;alter table public.clinical_results enable row level security;alter table public.stores enable row level security;alter table public.products enable row level security;alter table public.stock_lots enable row level security;alter table public.stock_movements enable row level security;alter table public.prescriptions enable row level security;alter table public.prescription_items enable row level security;alter table public.dispenses enable row level security;
create policy "assigned ward read" on public.wards for select using(public.user_has_facility(facility_id));
create policy "assigned store read" on public.stores for select using(public.user_has_facility(facility_id));
-- Direct browser mutations remain denied. Privilege-aware posting functions will own ADT, result validation, dispensing, stock movement, and charges.
commit;
